#version 330

#moj_import <minecraft:fog.glsl>
#moj_import <minecraft:dynamictransforms.glsl>

// ---- OrangeGames FX (generated by tools/gen_fx_shaders.py) ----
#moj_import <minecraft:globals.glsl>
flat in int ogFx;
flat in int ogGui;
in vec2 ogLocal;
in vec2 ogParam;
in float ogChain;
in vec3 ogNrmV;
in vec3 ogPosV;
in vec3 ogCenterV;

vec3 og_hsv2rgb(vec3 c) {
    vec3 p = abs(fract(c.xxx + vec3(0.0, 2.0 / 3.0, 1.0 / 3.0)) * 6.0 - 3.0);
    return c.z * mix(vec3(1.0), clamp(p - 1.0, 0.0, 1.0), c.y);
}

float og_hue(vec3 c) {
    float mx = max(c.r, max(c.g, c.b));
    float mn = min(c.r, min(c.g, c.b));
    float d = mx - mn;
    if (d < 1e-4) {
        return 0.0;
    }
    float h;
    if (mx == c.r) {
        h = mod((c.g - c.b) / d, 6.0);
    } else if (mx == c.g) {
        h = (c.b - c.r) / d + 2.0;
    } else {
        h = (c.r - c.g) / d + 4.0;
    }
    return h / 6.0;
}

float og_bayer(vec2 p) {
    int x = int(mod(p.x, 4.0));
    int y = int(mod(p.y, 4.0));
    int i = x + y * 4;
    float v = 0.0;
    if (i == 0) v = 0.0; else if (i == 1) v = 8.0; else if (i == 2) v = 2.0; else if (i == 3) v = 10.0;
    else if (i == 4) v = 12.0; else if (i == 5) v = 4.0; else if (i == 6) v = 14.0; else if (i == 7) v = 6.0;
    else if (i == 8) v = 3.0; else if (i == 9) v = 11.0; else if (i == 10) v = 1.0; else if (i == 11) v = 9.0;
    else if (i == 12) v = 15.0; else if (i == 13) v = 7.0; else if (i == 14) v = 13.0; else v = 5.0;
    return (v + 0.5) / 16.0;
}

float og_hash(float n) {
    return fract(sin(n) * 43758.5453);
}

vec3 og_rotY(vec3 v, float a) {
    float c = cos(a);
    float s = sin(a);
    return vec3(c * v.x + s * v.z, v.y, -s * v.x + c * v.z);
}

vec3 og_rotX(vec3 v, float a) {
    float c = cos(a);
    float s = sin(a);
    return vec3(v.x, c * v.y - s * v.z, s * v.y + c * v.z);
}

// End-portal style parallax starfield looked up by world-space direction: eight
// layers of hashed specks, each rotating at its own speed, teal -> violet, over
// deep space. charge warms the field toward white-gold.
vec3 og_portal(vec3 dir, float t, float charge) {
    vec3 col = vec3(0.015, 0.01, 0.05);
    for (int i = 0; i < 8; i++) {
        float fi = float(i);
        vec3 d = og_rotY(dir, t * (0.004 + 0.0025 * fi) + fi * 0.9);
        d = og_rotX(d, fi * 0.55 + t * 0.0015 * fi);
        vec2 uv = vec2(atan(d.z, d.x), asin(clamp(d.y, -1.0, 1.0))) * (2.5 + fi * 1.3);
        vec2 cell = floor(uv);
        vec2 f = fract(uv) - 0.5;
        float h = og_hash(dot(cell, vec2(127.1, 311.7)) + fi * 19.19);
        vec2 sp = (vec2(og_hash(h * 7.0), og_hash(h * 13.0)) - 0.5) * 0.8;
        float dist = length(f - sp);
        float star = smoothstep(0.16 - fi * 0.01, 0.0, dist) * step(0.55, h);
        float tw = 0.7 + 0.3 * sin(t * 0.3 + h * 40.0);
        vec3 lc = mix(vec3(0.05, 0.45, 0.6), vec3(0.75, 0.35, 1.0), fract(fi * 0.37 + 0.15));
        lc = mix(lc, vec3(1.0), step(0.93, h) * 0.6);
        col += star * lc * tw * (0.55 - fi * 0.04);
    }
    col = mix(col, col * vec3(1.5, 1.25, 0.9) + vec3(0.18, 0.1, 0.02), charge * 0.55);
    return col;
}

// Returns the FX colour; alpha <= 0 means the caller discards.
vec4 og_fx(vec4 tex) {
    float t = GameTime * 24000.0; // ticks
    if (ogGui == 1) {
        return tex; // static inventory look
    }
    if (ogFx == 1) {
        // prism core: hue baked in the texture + time, saturated and bright
        float h = fract(og_hue(tex.rgb) + t * 0.02);
        return vec4(og_hsv2rgb(vec3(h, 0.75, 1.0)) * 1.15, tex.a);
    }
    if (ogFx == 2) {
        // prism slash: spectrum sweep + dither dissolve (param.x 0..1)
        if (tex.a < 0.1) {
            return vec4(0.0);
        }
        float fade = ogParam.x;
        if (fade > og_bayer(gl_FragCoord.xy) * 0.98) {
            return vec4(0.0);
        }
        float h = fract(ogLocal.x * 0.8 + ogLocal.y * 0.2 + t * 0.05);
        vec3 c = og_hsv2rgb(vec3(h, 0.6, 1.0));
        return vec4(c * 1.1, tex.a * (1.0 - fade * 0.5));
    }
    if (ogFx == 3) {
        // nova orb: procedural plasma + rim glow, blue -> white with charge
        vec2 p = ogLocal * 6.2831;
        float w = sin(p.x * 1.5 + t * 0.25) + sin(p.y * 2.0 - t * 0.31) + sin((p.x + p.y) * 1.2 + t * 0.17);
        w = w / 3.0 * 0.5 + 0.5;
        float rim = 1.0 - abs(dot(normalize(ogNrmV), normalize(-ogPosV)));
        vec3 cold = vec3(0.25, 0.55, 1.0);
        vec3 hot = vec3(0.95, 0.98, 1.0);
        vec3 c = mix(cold, hot, clamp(w * 0.6 + ogParam.x * 0.6, 0.0, 1.0));
        c += rim * rim * vec3(0.6, 0.8, 1.0);
        float a = clamp(0.55 + 0.45 * w + rim * 0.4, 0.0, 1.0) * tex.a * (1.0 - ogParam.y);
        return vec4(c * (1.2 - 0.5 * ogParam.y), a);
    }
    if (ogFx == 4) {
        // nova ring: band from the texture, dissolves as param.x rises, hue by charge (param.y)
        if (tex.a < 0.1) {
            return vec4(0.0);
        }
        float fade = ogParam.x;
        if (fade > og_bayer(gl_FragCoord.xy) * 0.98) {
            return vec4(0.0);
        }
        vec2 d = ogLocal - 0.5;
        float r = length(d) * 2.0;
        float h = mix(0.58, 0.08, ogParam.y); // blue at low charge -> orange at full
        vec3 c = og_hsv2rgb(vec3(h, 0.5, 1.0));
        float pulse = 0.8 + 0.2 * sin(t * 0.8 + r * 12.0);
        return vec4(c * 1.2 * pulse, tex.a * (1.0 - fade));
    }
    if (ogFx == 5) {
        // tesla bolt: flickering white-blue core, dissolves by param.x
        float fade = ogParam.x;
        if (fade > og_bayer(gl_FragCoord.xy) * 0.98) {
            return vec4(0.0);
        }
        float flick = 0.6 + 0.4 * og_hash(floor(t * 3.0));
        float core = 1.0 - abs(ogLocal.y - 0.5) * 2.0;
        vec3 c = mix(vec3(0.5, 0.7, 1.0), vec3(1.0), core * core);
        return vec4(c * 1.3 * flick, tex.a * flick);
    }
    if (ogFx == 6) {
        // tesla coil orb: crackle pulse with sparse sparks
        float pulse = 0.7 + 0.3 * sin(t * 0.75);
        float cell = floor(ogLocal.x * 8.0) * 7.0 + floor(ogLocal.y * 8.0) * 13.0;
        float spark = step(0.96, og_hash(floor(t * 2.0) + cell));
        vec3 c = tex.rgb * pulse + spark * vec3(0.8, 0.9, 1.0);
        return vec4(c, tex.a);
    }
    if (ogFx == 10) {
        // per-viewer screen overlay. param.x = age/intensity, param.y = variant
        vec2 uv = gl_FragCoord.xy / ScreenSize;
        vec2 cuv = (uv - 0.5) * vec2(ScreenSize.x / ScreenSize.y, 1.0);
        float r = length(cuv);
        float age = ogParam.x;
        int variant = int(ogParam.y * 15.0 + 0.5);
        vec4 o = vec4(0.0);
        if (variant == 0) {
            // shockwave ring expanding from the centre
            float radius = age * 1.3;
            float band = exp(-pow((r - radius) * 14.0, 2.0));
            float inner = smoothstep(radius, radius - 0.25, r) * 0.25;
            o = vec4(mix(vec3(1.0, 0.9, 0.6), vec3(1.0), band), (band * 0.85 + inner) * (1.0 - age));
        } else if (variant == 1) {
            // rainbow vignette sweep
            float ang = atan(cuv.y, cuv.x) / 6.2831;
            vec3 c = og_hsv2rgb(vec3(fract(ang + t * 0.04 + r * 0.5), 0.8, 1.0));
            float vig = smoothstep(0.35, 0.95, r);
            o = vec4(c, vig * 0.65 * (1.0 - age));
        } else if (variant == 2) {
            // charge vignette, intensity = age
            float vig = smoothstep(0.3, 0.9, r);
            float pulse = 0.8 + 0.2 * sin(t * 0.9);
            o = vec4(vec3(0.35, 0.6, 1.0), vig * age * 0.55 * pulse);
        } else if (variant == 3) {
            // glitch: scanline bands with rgb split + red vignette
            float row = floor(uv.y * 48.0);
            float g = og_hash(row * 3.7 + floor(t * 4.0));
            float band = step(0.82, g);
            float stripe = step(0.5, fract(uv.x * 6.0 + (g - 0.5) * 0.8));
            vec3 c = mix(vec3(0.2, 0.9, 1.0), vec3(1.0, 0.2, 0.25), stripe);
            float vig = smoothstep(0.4, 1.0, r) * 0.5;
            o = vec4(mix(vec3(1.0, 0.3, 0.3), c, band), (band * 0.35 + vig) * (1.0 - age));
        } else {
            // white flash
            o = vec4(1.0, 1.0, 1.0, 0.7 * (1.0 - age) * (1.0 - age));
        }
        if (o.a < 0.03) {
            return vec4(0.0); // discard: keeps depth untouched where nothing is drawn
        }
        return o;
    }
    if (ogFx == 11) {
        // gpu sparks: palette by param.y (0 rainbow, 1 plasma, 2 electric), fade by age
        float age = clamp(ogParam.x + fract(t) / 15.0, 0.0, 1.0);
        int pal = int(ogParam.y * 15.0 + 0.5);
        vec3 c;
        if (pal == 0) {
            c = og_hsv2rgb(vec3(fract(ogChain * 8.0 + t * 0.05), 0.8, 1.0));
        } else if (pal == 1) {
            c = mix(vec3(0.4, 0.7, 1.0), vec3(1.0), og_hash(ogChain * 31.0));
        } else {
            c = mix(vec3(0.6, 0.8, 1.0), vec3(1.0), step(0.5, og_hash(floor(t * 2.0) + ogChain * 13.0)));
        }
        float flick = 0.7 + 0.3 * og_hash(floor(t * 2.0) + ogChain * 5.0);
        return vec4(c * 1.4 * flick, (1.0 - age) * (1.0 - age) * tex.a);
    }
    if (ogFx == 14) {
        // nova sphere: ray-cast a sphere of radius (charge) around the billboard centre;
        // surface = refracted parallax starfield + fresnel rim in the charge colour
        vec3 rd = normalize(ogPosV);
        vec3 c = ogCenterV;
        float r = (0.16 + 0.34 * ogParam.x) * (1.0 - 0.85 * ogParam.y);
        float b = dot(rd, c);
        float det = b * b - dot(c, c) + r * r;
        if (det < 0.0) {
            return vec4(0.0);
        }
        float th = b - sqrt(det);
        if (th < 0.05) {
            return vec4(0.0);
        }
        vec3 p = rd * th;
        vec3 n = (p - c) / r;
        vec3 refr = refract(rd, n, 0.74);
        vec3 dw = transpose(mat3(ModelViewMat)) * refr;
        vec3 col = og_portal(dw, t, ogParam.x);
        float fres = pow(1.0 - max(dot(n, -rd), 0.0), 3.0);
        vec3 rimCol = mix(vec3(0.3, 0.6, 1.0), vec3(1.0, 0.92, 0.7), ogParam.x);
        col += fres * rimCol * 1.3;
        col += (0.15 + 0.25 * ogParam.x) * rimCol * (0.6 + 0.4 * sin(t * 0.5));
        float a = (0.9 + 0.1 * fres) * (1.0 - ogParam.y);
        return vec4(col, a);
    }
    if (ogFx == 12) {
        // blade swing ghost: hue-shifted translucent copy, fades with param.x, hue offset param.y
        float h = fract(og_hue(tex.rgb) + t * 0.03 + ogParam.y * 0.3);
        vec3 c = og_hsv2rgb(vec3(h, 0.55, 1.0));
        float a = tex.a * 0.55 * (1.0 - ogParam.x);
        if (a < 0.02) {
            return vec4(0.0);
        }
        return vec4(c * 1.1, a);
    }
    return tex;
}

// holo edge (FX 13): chromatic split (neighbour samples passed in from main), scanlines, rare flicker
vec4 og_holo(vec4 tex, float rr, float bb) {
    float t = GameTime * 24000.0;
    if (ogGui == 1) {
        return tex;
    }
    vec3 c = vec3(rr, tex.g, bb);
    float scan = 0.88 + 0.12 * sin(gl_FragCoord.y * 1.7 + t * 1.5);
    float flick = 1.0 - 0.25 * step(0.985, og_hash(floor(t * 1.5)));
    return vec4(c * 1.12 * scan * flick, tex.a);
}
// ---- end OrangeGames FX decl ----

uniform sampler2D Sampler0;

#if defined(ALPHA_CUTOUT) && !defined(EMISSIVE) && !defined(NO_OVERLAY) && !defined(APPLY_TEXTURE_MATRIX)
#define MAYBE_PLAYERDISP 1
#endif

#ifdef DISSOLVE
uniform sampler2D DissolveMaskSampler;
#endif

in float sphericalVertexDistance;
in float cylindricalVertexDistance;

#ifdef PER_FACE_LIGHTING
in vec4 vertexPerFaceColorBack;
in vec4 vertexPerFaceColorFront;
#else
in vec4 vertexColor;
#endif

#ifndef EMISSIVE
in vec4 lightMapColor;
#endif

#ifndef NO_OVERLAY
in vec4 overlayColor;
#endif

in vec2 texCoord0;

out vec4 fragColor;

#ifdef MAYBE_PLAYERDISP
in vec2 texCoord1;
in float part;

#define FADERANGE 12.0
#define FADEBIAS 8.0
#define MINALPHA 0.25

const mat4 bayer4 = mat4( 0.0 / 16.0,  8.0 / 16.0,  2.0 / 16.0, 10.0 / 16.0,
12.0 / 16.0,  4.0 / 16.0, 14.0 / 16.0,  6.0 / 16.0,
3.0 / 16.0, 11.0 / 16.0,  1.0 / 16.0,  9.0 / 16.0,
15.0 / 16.0,  7.0 / 16.0, 13.0 / 16.0,  5.0 / 16.0);

#endif

void main() {
    vec4 color = texture(Sampler0, texCoord0);

    // ---- OrangeGames FX ----
    if (ogFx != 0) {
        vec4 ogC;
        if (ogFx == 13) {
            vec2 ogPx = 1.0 / vec2(textureSize(Sampler0, 0));
            float ogOff = 0.6 + 0.6 * sin(GameTime * 24000.0 * 0.7);
            ogC = og_holo(color,
                          texture(Sampler0, texCoord0 + vec2(ogPx.x * ogOff, 0.0)).r,
                          texture(Sampler0, texCoord0 - vec2(ogPx.x * ogOff, 0.0)).b);
        } else {
            ogC = og_fx(color);
        }
        if (ogC.a <= 0.0) {
            discard;
        }
        ogC *= ColorModulator;
#ifndef NO_OVERLAY
        ogC.rgb = mix(overlayColor.rgb, ogC.rgb, overlayColor.a);
#endif
        fragColor = apply_fog(ogC, sphericalVertexDistance, cylindricalVertexDistance, FogEnvironmentalStart, FogEnvironmentalEnd, FogRenderDistanceStart, FogRenderDistanceEnd, FogColor);
        return;
    }
    // ---- end OrangeGames FX ----
#ifdef ALPHA_CUTOUT
    if (color.a < ALPHA_CUTOUT) {
        discard;
    }
#endif

#ifdef PER_FACE_LIGHTING
    vec4 faceVertexColor = gl_FrontFacing ? vertexPerFaceColorFront : vertexPerFaceColorBack;
#else
    vec4 faceVertexColor = vertexColor;
#endif

#ifdef DISSOLVE
    if (faceVertexColor.a < texture(DissolveMaskSampler, texCoord0).a) {
        discard;
    }
    // The dissolve effect entirely replaces translucency
    faceVertexColor.a = 1.0;
#endif

    color *= faceVertexColor * ColorModulator;
#ifndef NO_OVERLAY
    color.rgb = mix(overlayColor.rgb, color.rgb, overlayColor.a);
#endif
#ifndef EMISSIVE
    color *= lightMapColor;
#endif

    fragColor = apply_fog(color, sphericalVertexDistance, cylindricalVertexDistance, FogEnvironmentalStart, FogEnvironmentalEnd, FogRenderDistanceStart, FogRenderDistanceEnd, FogColor);

    #ifdef MAYBE_PLAYERDISP
    if (part > 1.0 - 10e-6 && fragColor.a < 1.0) {
        fragColor.a = max(fragColor.a, MINALPHA);

        vec3 underCol = texture(Sampler0, texCoord1).rgb;
        vec3 trueMix = mix(underCol, fragColor.rgb, fragColor.a);
        float fade = mix(fragColor.a, 1.0, clamp((cylindricalVertexDistance - FADEBIAS) / (FADERANGE - FADEBIAS), 0.0, 1.0));

        fragColor = vec4((trueMix - (1 - fade) * underCol) / fade,  fade);
        if (fragColor.a < bayer4[int(gl_FragCoord.x) % 4][int(gl_FragCoord.y) % 4] + (0.5 / 16.0)) {
            discard;
        }
        else {
            fragColor.a = 1.0;
        }
    }
    #endif
}
