#version 150

#moj_import <minecraft:fog.glsl>
#moj_import <minecraft:dynamictransforms.glsl>

// ---- OrangeGames FX (generated by tools/gen_fx_shaders.py) ----
#moj_import <minecraft:globals.glsl>
flat in int ogFx;
flat in int ogGui;
in vec2 ogLocal;
in vec2 ogParam;
in float ogChain;
in vec3 ogNrmV;
in vec3 ogPosV;

vec3 og_hsv2rgb(vec3 c) {
    vec3 p = abs(fract(c.xxx + vec3(0.0, 2.0 / 3.0, 1.0 / 3.0)) * 6.0 - 3.0);
    return c.z * mix(vec3(1.0), clamp(p - 1.0, 0.0, 1.0), c.y);
}

float og_hue(vec3 c) {
    float mx = max(c.r, max(c.g, c.b));
    float mn = min(c.r, min(c.g, c.b));
    float d = mx - mn;
    if (d < 1e-4) {
        return 0.0;
    }
    float h;
    if (mx == c.r) {
        h = mod((c.g - c.b) / d, 6.0);
    } else if (mx == c.g) {
        h = (c.b - c.r) / d + 2.0;
    } else {
        h = (c.r - c.g) / d + 4.0;
    }
    return h / 6.0;
}

float og_bayer(vec2 p) {
    int x = int(mod(p.x, 4.0));
    int y = int(mod(p.y, 4.0));
    int i = x + y * 4;
    float v = 0.0;
    if (i == 0) v = 0.0; else if (i == 1) v = 8.0; else if (i == 2) v = 2.0; else if (i == 3) v = 10.0;
    else if (i == 4) v = 12.0; else if (i == 5) v = 4.0; else if (i == 6) v = 14.0; else if (i == 7) v = 6.0;
    else if (i == 8) v = 3.0; else if (i == 9) v = 11.0; else if (i == 10) v = 1.0; else if (i == 11) v = 9.0;
    else if (i == 12) v = 15.0; else if (i == 13) v = 7.0; else if (i == 14) v = 13.0; else v = 5.0;
    return (v + 0.5) / 16.0;
}

float og_hash(float n) {
    return fract(sin(n) * 43758.5453);
}

// Returns the FX colour; alpha <= 0 means the caller discards.
vec4 og_fx(vec4 tex) {
    float t = GameTime * 24000.0; // ticks
    if (ogGui == 1) {
        return tex; // static inventory look
    }
    if (ogFx == 1) {
        // prism core: hue baked in the texture + time, saturated and bright
        float h = fract(og_hue(tex.rgb) + t * 0.02);
        return vec4(og_hsv2rgb(vec3(h, 0.75, 1.0)) * 1.15, tex.a);
    }
    if (ogFx == 2) {
        // prism slash: spectrum sweep + dither dissolve (param.x 0..1)
        if (tex.a < 0.1) {
            return vec4(0.0);
        }
        float fade = ogParam.x;
        if (fade > og_bayer(gl_FragCoord.xy) * 0.98) {
            return vec4(0.0);
        }
        float h = fract(ogLocal.x * 0.8 + ogLocal.y * 0.2 + t * 0.05);
        vec3 c = og_hsv2rgb(vec3(h, 0.6, 1.0));
        return vec4(c * 1.1, tex.a * (1.0 - fade * 0.5));
    }
    if (ogFx == 3) {
        // nova orb: procedural plasma + rim glow, blue -> white with charge
        vec2 p = ogLocal * 6.2831;
        float w = sin(p.x * 1.5 + t * 0.25) + sin(p.y * 2.0 - t * 0.31) + sin((p.x + p.y) * 1.2 + t * 0.17);
        w = w / 3.0 * 0.5 + 0.5;
        float rim = 1.0 - abs(dot(normalize(ogNrmV), normalize(-ogPosV)));
        vec3 cold = vec3(0.25, 0.55, 1.0);
        vec3 hot = vec3(0.95, 0.98, 1.0);
        vec3 c = mix(cold, hot, clamp(w * 0.6 + ogParam.x * 0.6, 0.0, 1.0));
        c += rim * rim * vec3(0.6, 0.8, 1.0);
        float a = clamp(0.55 + 0.45 * w + rim * 0.4, 0.0, 1.0) * tex.a;
        return vec4(c * 1.2, a);
    }
    if (ogFx == 4) {
        // nova ring: band from the texture, dissolves as param.x rises, hue by charge (param.y)
        if (tex.a < 0.1) {
            return vec4(0.0);
        }
        float fade = ogParam.x;
        if (fade > og_bayer(gl_FragCoord.xy) * 0.98) {
            return vec4(0.0);
        }
        vec2 d = ogLocal - 0.5;
        float r = length(d) * 2.0;
        float h = mix(0.58, 0.08, ogParam.y); // blue at low charge -> orange at full
        vec3 c = og_hsv2rgb(vec3(h, 0.5, 1.0));
        float pulse = 0.8 + 0.2 * sin(t * 0.8 + r * 12.0);
        return vec4(c * 1.2 * pulse, tex.a * (1.0 - fade));
    }
    if (ogFx == 5) {
        // tesla bolt: flickering white-blue core, dissolves by param.x
        float fade = ogParam.x;
        if (fade > og_bayer(gl_FragCoord.xy) * 0.98) {
            return vec4(0.0);
        }
        float flick = 0.6 + 0.4 * og_hash(floor(t * 3.0));
        float core = 1.0 - abs(ogLocal.y - 0.5) * 2.0;
        vec3 c = mix(vec3(0.5, 0.7, 1.0), vec3(1.0), core * core);
        return vec4(c * 1.3 * flick, tex.a * flick);
    }
    if (ogFx == 6) {
        // tesla coil orb: crackle pulse with sparse sparks
        float pulse = 0.7 + 0.3 * sin(t * 0.75);
        float cell = floor(ogLocal.x * 8.0) * 7.0 + floor(ogLocal.y * 8.0) * 13.0;
        float spark = step(0.96, og_hash(floor(t * 2.0) + cell));
        vec3 c = tex.rgb * pulse + spark * vec3(0.8, 0.9, 1.0);
        return vec4(c, tex.a);
    }
    return tex;
}
// ---- end OrangeGames FX decl ----

#if defined(ALPHA_CUTOUT) && !defined(EMISSIVE) && !defined(NO_OVERLAY) && !defined(APPLY_TEXTURE_MATRIX)
#define MAYBE_PLAYERDISP 1
#endif

uniform sampler2D Sampler0;

in float sphericalVertexDistance;
in float cylindricalVertexDistance;
in vec4 vertexColor;
in vec4 lightMapColor;
in vec4 overlayColor;
in vec2 texCoord0;
#ifdef MAYBE_PLAYERDISP
in vec2 texCoord1;
in float part;

#define FADERANGE 12.0
#define FADEBIAS 8.0
#define MINALPHA 0.25

const mat4 bayer4 = mat4( 0.0 / 16.0,  8.0 / 16.0,  2.0 / 16.0, 10.0 / 16.0,
12.0 / 16.0,  4.0 / 16.0, 14.0 / 16.0,  6.0 / 16.0,
3.0 / 16.0, 11.0 / 16.0,  1.0 / 16.0,  9.0 / 16.0,
15.0 / 16.0,  7.0 / 16.0, 13.0 / 16.0,  5.0 / 16.0);

#endif

out vec4 fragColor;

void main() {
    vec4 color = texture(Sampler0, texCoord0);

    // ---- OrangeGames FX ----
    if (ogFx != 0) {
        vec4 ogC = og_fx(color);
        if (ogC.a <= 0.0) {
            discard;
        }
        ogC *= ColorModulator;
#ifndef NO_OVERLAY
        ogC.rgb = mix(overlayColor.rgb, ogC.rgb, overlayColor.a);
#endif
        fragColor = apply_fog(ogC, sphericalVertexDistance, cylindricalVertexDistance, FogEnvironmentalStart, FogEnvironmentalEnd, FogRenderDistanceStart, FogRenderDistanceEnd, FogColor);
        return;
    }
    // ---- end OrangeGames FX ----
    #ifdef ALPHA_CUTOUT
    if (color.a < ALPHA_CUTOUT) {
        discard;
    }
    #endif
    color *= vertexColor * ColorModulator;
    #ifndef NO_OVERLAY
    color.rgb = mix(overlayColor.rgb, color.rgb, overlayColor.a);
    #endif
    #ifndef EMISSIVE
    color *= lightMapColor;
    #endif
    fragColor = apply_fog(color, sphericalVertexDistance, cylindricalVertexDistance, FogEnvironmentalStart, FogEnvironmentalEnd, FogRenderDistanceStart, FogRenderDistanceEnd, FogColor);

    #ifdef MAYBE_PLAYERDISP
    if (part > 1.0 - 10e-6 && fragColor.a < 1.0) {
        fragColor.a = max(fragColor.a, MINALPHA);

        vec3 underCol = texture(Sampler0, texCoord1).rgb;
        vec3 trueMix = mix(underCol, fragColor.rgb, fragColor.a);
        float fade = mix(fragColor.a, 1.0, clamp((cylindricalVertexDistance - FADEBIAS) / (FADERANGE - FADEBIAS), 0.0, 1.0));

        fragColor = vec4((trueMix - (1 - fade) * underCol) / fade,  fade);
        if (fragColor.a < bayer4[int(gl_FragCoord.x) % 4][int(gl_FragCoord.y) % 4] + (0.5 / 16.0)) {
            discard;
        }
        else {
            fragColor.a = 1.0;
        }
    }
    #endif
}