#version 150

#moj_import <minecraft:light.glsl>
#moj_import <minecraft:fog.glsl>
#moj_import <minecraft:dynamictransforms.glsl>
#moj_import <minecraft:projection.glsl>

// ---- OrangeGames FX (generated by tools/gen_fx_shaders.py) ----
#moj_import <minecraft:globals.glsl>
flat out int ogFx;
flat out int ogGui;
out vec2 ogLocal;
out vec2 ogParam;
out float ogChain;
out vec3 ogNrmV;
out vec3 ogPosV;
// ---- end OrangeGames FX decl ----

#if defined(ALPHA_CUTOUT) && !defined(EMISSIVE) && !defined(NO_OVERLAY) && !defined(APPLY_TEXTURE_MATRIX)
#define MAYBE_PLAYERDISP 1
#endif

#define SPLITMODEL 0

in vec3 Position;
in vec4 Color;
in vec2 UV0;
in ivec2 UV1;
in ivec2 UV2;
in vec3 Normal;

#ifdef MAYBE_PLAYERDISP
uniform sampler2D Sampler0;
#endif
uniform sampler2D Sampler1;
uniform sampler2D Sampler2;

out float sphericalVertexDistance;
out float cylindricalVertexDistance;
out vec4 vertexColor;
out vec4 lightMapColor;
out vec4 overlayColor;
out vec2 texCoord0;
#ifdef MAYBE_PLAYERDISP
out vec2 texCoord1;
out float part;

#define SPACING 1024.0
#define MAXRANGE (0.5 * SPACING)
#define SKINRES 64
#define FACERES 8

#define SLIMCHECK0 vec2(54.0 / float(SKINRES), 20.0 / float(SKINRES))
#define SLIMCHECK1 vec2(55.0 / float(SKINRES), 20.0 / float(SKINRES))

const vec4[] subuvs = vec4[](
vec4(4.0,  0.0,  8.0,  4.0 ), // 4x4x12
vec4(8.0,  0.0,  12.0, 4.0 ),
vec4(0.0,  4.0,  4.0,  16.0),
vec4(4.0,  4.0,  8.0,  16.0),
vec4(8.0,  4.0,  12.0, 16.0),
vec4(12.0, 4.0,  16.0, 16.0),
vec4(4.0,  0.0,  7.0,  4.0 ), // 4x3x12
vec4(7.0,  0.0,  10.0, 4.0 ),
vec4(0.0,  4.0,  4.0,  16.0),
vec4(4.0,  4.0,  7.0,  16.0),
vec4(7.0,  4.0,  11.0, 16.0),
vec4(11.0, 4.0,  14.0, 16.0),
vec4(4.0,  0.0,  12.0, 4.0 ), // 4x8x12
vec4(12.0,  0.0, 20.0, 4.0 ),
vec4(0.0,  4.0,  4.0,  16.0),
vec4(4.0,  4.0,  12.0, 16.0),
vec4(12.0, 4.0,  16.0, 16.0),
vec4(16.0, 4.0,  24.0, 16.0)
);

const vec2[] origins = vec2[](
vec2(40.0, 16.0), // right arm
vec2(40.0, 32.0),
vec2(32.0, 48.0), // left arm
vec2(48.0, 48.0),
vec2(40.0, 16.0), // slim right arm
vec2(40.0, 32.0),
vec2(32.0, 48.0), // slim left arm
vec2(48.0, 48.0),
vec2(16.0, 16.0), // torso
vec2(16.0, 32.0),
vec2(0.0,  16.0), // right leg
vec2(0.0,  32.0),
vec2(16.0, 48.0), // left leg
vec2(0.0,  48.0)
);

const int[] faceremap = int[](0, 0, 1, 1, 2, 3, 4, 5);
#endif

void main() {
    #ifdef NO_CARDINAL_LIGHTING
    vertexColor = Color;
    #else
    vertexColor = minecraft_mix_light(Light0_Direction, Light1_Direction, Normal, Color);
    #endif
    lightMapColor = texelFetch(Sampler2, UV2 / 16, 0);
    overlayColor = texelFetch(Sampler1, UV1, 0);

    #ifdef MAYBE_PLAYERDISP
    ivec2 dim = textureSize(Sampler0, 0);
    part = 0.0;
    texCoord1 = vec2(0.0);

    // check world projmat (not gui), 64x64 texture (player tex dim), valid fog (not hand)
    if (abs(ProjMat[2][3]) > 10e-6 && dim.x == SKINRES && dim.y == SKINRES && FogRenderDistanceEnd > FogRenderDistanceStart) {
        int partId = -int((Position.y - MAXRANGE) / SPACING);

        part = float(partId);

        if (partId != 0) {
            partId -= 1;
            // vec4 samp1 = texture(Sampler0, SLIMCHECK0);
            // vec4 samp2 = texture(Sampler0, SLIMCHECK1);
            bool slim = partId == 2 || partId == 3; //samp1.a == 0.0 || (((samp1.r + samp1.g + samp1.b) == 0.0) && ((samp2.r + samp2.g + samp2.b) == 0.0) && samp1.a == 1.0 && samp2.a == 1.0);
            int partIdMod = partId % 7;
            int outerLayer = (gl_VertexID / 24) % 2;
            int vertexId = gl_VertexID % 4;
            int faceId = (gl_VertexID % 24) / 4;
            ivec2 faceIdTmp = ivec2(round(UV0 * SKINRES));

            // find the desired part UV origin
            vec2 UVout = origins[2 * partIdMod + outerLayer];
            vec2 UVout2 = origins[2 * partIdMod];

            // find the player head face UV origin
            if ((faceId != 1 && vertexId >= 2) || (faceId == 1 && vertexId <= 1)) {
                faceIdTmp.y -= FACERES;
            }
            if (vertexId == 0 || vertexId == 3) {
                faceIdTmp.x -= FACERES;
            }

            // calculate a faceId based on face UV origin
            faceIdTmp /= FACERES;
            faceId = (faceIdTmp.x % 4) + 4 * faceIdTmp.y;
            faceId = faceremap[faceId];
            int subuvIndex = faceId;

            if (slim) { // select slim arms
                subuvIndex += 6;
            }
            else if (partIdMod == 4) { // select torso
                subuvIndex += 12;
            }

            vec4 subuv = subuvs[subuvIndex];
            vec2 offset = vec2(0.0);

            #if SPLITMODEL == 1
            // adjust UVs in split cases
            if (faceId >= 2) {
                subuv.w -= 6.0;
                if (partId >= 5) {
                    subuv.yw += 6.0;
                }
            }
            #endif

            // find the UV offset within the current part
            if (faceId == 1) {
                if (vertexId == 0) {
                    offset += subuv.zw;
                }
                else if (vertexId == 1) {
                    offset += subuv.xw;
                }
                else if (vertexId == 2) {
                    offset += subuv.xy;
                }
                else {
                    offset += subuv.zy;
                }
            }
            else {
                if (vertexId == 0) {
                    offset += subuv.zy;
                }
                else if (vertexId == 1) {
                    offset += subuv.xy;
                }
                else if (vertexId == 2) {
                    offset += subuv.xw;
                }
                else {
                    offset += subuv.zw;
                }
            }

            // apply offset to part origin and normalize
            UVout += offset;
            UVout2 += offset;
            UVout /= float(SKINRES);
            UVout2 /= float(SKINRES);

            // assign output
            vec3 wpos = Position;
            wpos.y += SPACING * (partId + 1);
            gl_Position = ProjMat * ModelViewMat * vec4(wpos, 1.0);

            sphericalVertexDistance = fog_spherical_distance(wpos);
            cylindricalVertexDistance = fog_cylindrical_distance(wpos);

            texCoord0 = UVout;
            texCoord1 = UVout2;

            return;
        }
    }
    #endif

    gl_Position = ProjMat * ModelViewMat * vec4(Position, 1.0);

    sphericalVertexDistance = fog_spherical_distance(Position);
    cylindricalVertexDistance = fog_cylindrical_distance(Position);

    texCoord0 = UV0;
    #ifdef APPLY_TEXTURE_MATRIX
    texCoord0 = (TextureMat * vec4(UV0, 0.0, 1.0)).xy;
    #endif

    // ---- OrangeGames FX ----
    ogFx = 0;
    ogGui = (abs(ProjMat[2][3]) < 10e-6) ? 1 : 0;
    int ogCorner = gl_VertexID % 4;
    ogLocal = vec2(ogCorner >= 2 ? 1.0 : 0.0, (ogCorner == 1 || ogCorner == 2) ? 1.0 : 0.0);
    ogChain = ogLocal.x;
    ogParam = vec2(float(UV2.x >> 4), float(UV2.y >> 4)) / 15.0;
    ogNrmV = normalize((ModelViewMat * vec4(Normal, 0.0)).xyz);
    ogPosV = (ModelViewMat * vec4(Position, 1.0)).xyz;
    float ogG = Color.g * 255.0;
    if (Color.r > 0.999 && ogG > 199.5 && ogG < 254.5) {
        ogFx = int(Color.b * 255.0 + 0.5);
        float ogSub = 254.0 - floor(ogG + 0.5);
        ogChain = (ogSub + ogLocal.x) / 8.0;
        float ogT = GameTime * 24000.0; // ticks, fractional
        vertexColor = vec4(1.0);
#ifndef EMISSIVE
        lightMapColor = vec4(1.0);
#endif
        if (ogGui == 0) {
            vec3 ogDisp = vec3(0.0);
            if (ogFx == 3) {
                // nova orb: breathing pulse along the normal, stronger with charge
                ogDisp = Normal * (0.02 + 0.05 * ogParam.x) * sin(ogT * 0.9 + ogLocal.x * 6.2831 + ogLocal.y * 3.1);
            } else if (ogFx == 5) {
                // tesla bolt: per-frame jitter, pinned at both ends of the chain
                float ogSeed = floor(ogT * 3.0) * 17.0 + ogSub * 5.0 + float(ogCorner >= 2 ? 1 : 0) * 3.0 + ogParam.y * 97.0;
                vec3 ogH = fract(sin(vec3(ogSeed * 12.9898, ogSeed * 78.233, ogSeed * 37.719)) * 43758.5453) - 0.5;
                ogDisp = ogH * 0.45 * sin(3.14159 * ogChain);
            }
            if (ogFx == 3 || ogFx == 5) {
                gl_Position = ProjMat * ModelViewMat * vec4(Position + ogDisp, 1.0);
            }
            if (ogFx == 11) {
                // gpu sparks: every micro-cube (sub-index) flies its own hashed trajectory;
                // age = coarse per-tick param + sub-tick smoothing from GameTime
                float ogAge = clamp(ogParam.x + fract(ogT) / 15.0, 0.0, 1.0);
                vec3 ogHs = fract(sin(vec3(ogSub * 12.9898 + 1.0, ogSub * 78.233 + 2.0, ogSub * 37.719 + 3.0)) * 43758.5453);
                vec3 ogDir = normalize(ogHs - 0.5 + vec3(0.0, 0.15, 0.0));
                float ogSpd = 0.8 + fract(ogHs.x * 7.13) * 1.6;
                float ogEase = 1.0 - (1.0 - ogAge) * (1.0 - ogAge);
                vec3 ogFly = ogDir * ogSpd * ogEase * 2.2 + vec3(0.0, -1.6 * ogAge * ogAge, 0.0);
                gl_Position = ProjMat * ModelViewMat * vec4(Position + ogFly, 1.0);
            }
        }
        if (ogFx == 10) {
            // screen overlay: pin the quad just past the near plane, spanning the view
            if (ogGui == 0) {
                gl_Position = ProjMat * vec4((ogLocal.x * 2.0 - 1.0) * 0.32, (1.0 - ogLocal.y * 2.0) * 0.32, -0.06, 1.0);
            } else {
                gl_Position = vec4(0.0, 0.0, 0.0, 1.0); // degenerate: never drawn in inventories
            }
        }
    }
    // ---- end OrangeGames FX ----
}