#!/usr/bin/env python3
"""Inject OrangeGames FX into the vanilla ITEM core shaders.

Items (held, dropped, ItemDisplays, item frames) do NOT render through
core/entity - they use rendertype_item_entity_translucent_cull.{vsh,fsh} on
1.21.6-1.21.11 and item.{vsh,fsh} on 26.1+. The vanilla sources are vendored in
tools/vanilla_shaders/<ver>/ (extracted from the official client jars) and this
script writes ogfx_<ver>/assets/minecraft/shaders/core/<name>.{vsh,fsh}.
ModelEngine's entity shaders are left alone.

Only version families whose vanilla shader has been verified from a real jar
get an overlay (see VERSIONS); anything else renders the markers as a plain
near-white tint. A compile error disables the whole pack on that client, so
keep the GLSL conservative (#version follows the vanilla file).

Marker convention (shared with tools/gen_fx_art.py):
    vertex Color == (255, 254 - sub, 255 - FXID)/255   sub = 0..54, FXID = 1..15
    -> near-white when unshaded (Bedrock, unsupported Java versions)
    FX ids: 1 prism core, 2 prism slash, 3 (unused), 4 nova ring,
            5 tesla bolt, 6 tesla coil orb, 10 screen overlay (per-viewer
            fullscreen quad), 11 gpu sparks, 12 blade ghost, 13 holo edge,
            14 nova sphere (billboarded quad ray-cast as a sphere whose surface
            is a refracted parallax starfield - the end-portal look),
            15 tesla sphere (same, electric palette + crackle; param.y = zap surge)
Per-entity parameters ride in UV2 (ItemDisplay brightness): block light ->
ogParam.x, sky light -> ogParam.y, each 0..1 in 1/15 steps.
"""
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
# overlay dir -> (vanilla source dir, shader base name)
VERSIONS = {
    "1_21_8": ("1_21_8", "rendertype_item_entity_translucent_cull"),   # formats 64      (1.21.7-1.21.8)
    "1_21_11": ("1_21_11", "rendertype_item_entity_translucent_cull"), # formats 75-83   (1.21.11)
    "26_1": ("26_1", "item"),                                          # formats 84-87
    "26_2": ("26_2", "item"),                                          # formats 88+
}

VSH_DECL = """
// ---- OrangeGames FX (generated by tools/gen_fx_shaders.py) ----
#moj_import <minecraft:globals.glsl>
flat out int ogFx;
flat out int ogGui;
out vec2 ogLocal;
out vec2 ogParam;
out float ogChain;
out vec3 ogNrmV;
out vec3 ogPosV;
out vec3 ogCenterV;
// ---- end OrangeGames FX decl ----
"""

VSH_MAIN_TAIL = """
    // ---- OrangeGames FX ----
    ogFx = 0;
    ogGui = (abs(ProjMat[2][3]) < 10e-6) ? 1 : 0;
    int ogCorner = gl_VertexID % 4;
    ogLocal = vec2(ogCorner >= 2 ? 1.0 : 0.0, (ogCorner == 1 || ogCorner == 2) ? 1.0 : 0.0);
    ogChain = ogLocal.x;
    ogParam = vec2(float(UV2.x >> 4), float(UV2.y >> 4)) / 15.0;
    ogNrmV = normalize((ModelViewMat * vec4(Normal, 0.0)).xyz);
    ogPosV = (ModelViewMat * vec4(Position, 1.0)).xyz;
    ogCenterV = ogPosV;
    float ogG = Color.g * 255.0;
    float ogB = Color.b * 255.0;
    if (Color.r > 0.999 && ogG > 199.5 && ogG < 254.5 && ogB > 239.5 && ogB < 254.5) {
        ogFx = 255 - int(ogB + 0.5);
        float ogSub = 254.0 - floor(ogG + 0.5);
        ogChain = (ogSub + ogLocal.x) / 8.0;
        float ogT = GameTime * 24000.0; // ticks, fractional
%%VERTEX_COLOR%%
        if (ogGui == 0) {
            vec3 ogDisp = vec3(0.0);
            if (ogFx == 3) {
                // nova orb: breathing pulse along the normal, stronger with charge
                ogDisp = Normal * (0.02 + 0.05 * ogParam.x) * sin(ogT * 0.9 + ogLocal.x * 6.2831 + ogLocal.y * 3.1);
            } else if (ogFx == 5) {
                // tesla bolt: per-frame jitter, pinned at both ends of the chain
                float ogSeed = floor(ogT * 3.0) * 17.0 + ogSub * 5.0 + float(ogCorner >= 2 ? 1 : 0) * 3.0 + ogParam.y * 97.0;
                vec3 ogH = fract(sin(vec3(ogSeed * 12.9898, ogSeed * 78.233, ogSeed * 37.719)) * 43758.5453) - 0.5;
                ogDisp = ogH * 0.45 * sin(3.14159 * ogChain);
            }
            if (ogFx == 3 || ogFx == 5) {
                gl_Position = ProjMat * ModelViewMat * vec4(Position + ogDisp, 1.0);
            }
            if (ogFx == 11) {
                // gpu sparks: every micro-cube (sub-index) flies its own hashed trajectory;
                // age = coarse per-tick param + sub-tick smoothing from GameTime
                float ogAge = clamp(ogParam.x + fract(ogT) / 15.0, 0.0, 1.0);
                vec3 ogHs = fract(sin(vec3(ogSub * 12.9898 + 1.0, ogSub * 78.233 + 2.0, ogSub * 37.719 + 3.0)) * 43758.5453);
                vec3 ogDir = normalize(ogHs - 0.5 + vec3(0.0, 0.15, 0.0));
                float ogSpd = 0.8 + fract(ogHs.x * 7.13) * 1.6;
                float ogEase = 1.0 - (1.0 - ogAge) * (1.0 - ogAge);
                vec3 ogFly = ogDir * ogSpd * ogEase * 2.2 + vec3(0.0, -1.6 * ogAge * ogAge, 0.0);
                gl_Position = ProjMat * ModelViewMat * vec4(Position + ogFly, 1.0);
            }
        }
        if (ogFx == 10) {
            // screen overlay: pin the quad just past the near plane, spanning the view
            if (ogGui == 0) {
                gl_Position = ProjMat * vec4((ogLocal.x * 2.0 - 1.0) * 0.32, (1.0 - ogLocal.y * 2.0) * 0.32, -0.06, 1.0);
            } else {
                gl_Position = vec4(0.0, 0.0, 0.0, 1.0); // degenerate: never drawn in inventories
            }
        }
        if ((ogFx == 14 || ogFx == 15) && ogGui == 0) {
            // nova / tesla sphere: the model is one 2x2 quad in the XY plane (identity display transform).
            // Recover the quad centre from this vertex's corner (vanilla face vertex order), then
            // rebuild the quad as a camera-facing billboard around it; the fsh ray-casts the sphere.
            float ogSx = Normal.z > 0.0 ? 1.0 : -1.0;
            vec2 ogOff = vec2(ogSx * (ogLocal.x * 2.0 - 1.0), 1.0 - 2.0 * ogLocal.y);
            vec3 ogCw = Position - vec3(ogOff, 0.0);
            vec3 ogCv = (ModelViewMat * vec4(ogCw, 1.0)).xyz;
            vec3 ogPv = ogCv + vec3(ogOff, 0.0);
            ogCenterV = ogCv;
            ogPosV = ogPv;
            gl_Position = ProjMat * vec4(ogPv, 1.0);
        }
    }
    // ---- end OrangeGames FX ----
"""

FSH_DECL = """
// ---- OrangeGames FX (generated by tools/gen_fx_shaders.py) ----
#moj_import <minecraft:globals.glsl>
flat in int ogFx;
flat in int ogGui;
in vec2 ogLocal;
in vec2 ogParam;
in float ogChain;
in vec3 ogNrmV;
in vec3 ogPosV;
in vec3 ogCenterV;

vec3 og_hsv2rgb(vec3 c) {
    vec3 p = abs(fract(c.xxx + vec3(0.0, 2.0 / 3.0, 1.0 / 3.0)) * 6.0 - 3.0);
    return c.z * mix(vec3(1.0), clamp(p - 1.0, 0.0, 1.0), c.y);
}

float og_hue(vec3 c) {
    float mx = max(c.r, max(c.g, c.b));
    float mn = min(c.r, min(c.g, c.b));
    float d = mx - mn;
    if (d < 1e-4) {
        return 0.0;
    }
    float h;
    if (mx == c.r) {
        h = mod((c.g - c.b) / d, 6.0);
    } else if (mx == c.g) {
        h = (c.b - c.r) / d + 2.0;
    } else {
        h = (c.r - c.g) / d + 4.0;
    }
    return h / 6.0;
}

float og_bayer(vec2 p) {
    int x = int(mod(p.x, 4.0));
    int y = int(mod(p.y, 4.0));
    int i = x + y * 4;
    float v = 0.0;
    if (i == 0) v = 0.0; else if (i == 1) v = 8.0; else if (i == 2) v = 2.0; else if (i == 3) v = 10.0;
    else if (i == 4) v = 12.0; else if (i == 5) v = 4.0; else if (i == 6) v = 14.0; else if (i == 7) v = 6.0;
    else if (i == 8) v = 3.0; else if (i == 9) v = 11.0; else if (i == 10) v = 1.0; else if (i == 11) v = 9.0;
    else if (i == 12) v = 15.0; else if (i == 13) v = 7.0; else if (i == 14) v = 13.0; else v = 5.0;
    return (v + 0.5) / 16.0;
}

float og_hash(float n) {
    return fract(sin(n) * 43758.5453);
}

vec3 og_rotY(vec3 v, float a) {
    float c = cos(a);
    float s = sin(a);
    return vec3(c * v.x + s * v.z, v.y, -s * v.x + c * v.z);
}

vec3 og_rotX(vec3 v, float a) {
    float c = cos(a);
    float s = sin(a);
    return vec3(v.x, c * v.y - s * v.z, s * v.y + c * v.z);
}

// End-portal style parallax starfield looked up by world-space direction: eight
// layers of hashed specks, each rotating at its own speed, teal -> violet, over
// deep space. charge warms the field toward white-gold.
vec3 og_portal(vec3 dir, float t, float charge) {
    vec3 col = vec3(0.015, 0.01, 0.05);
    for (int i = 0; i < 8; i++) {
        float fi = float(i);
        vec3 d = og_rotY(dir, t * (0.004 + 0.0025 * fi) + fi * 0.9);
        d = og_rotX(d, fi * 0.55 + t * 0.0015 * fi);
        vec2 uv = vec2(atan(d.z, d.x), asin(clamp(d.y, -1.0, 1.0))) * (2.5 + fi * 1.3);
        vec2 cell = floor(uv);
        vec2 f = fract(uv) - 0.5;
        float h = og_hash(dot(cell, vec2(127.1, 311.7)) + fi * 19.19);
        vec2 sp = (vec2(og_hash(h * 7.0), og_hash(h * 13.0)) - 0.5) * 0.8;
        float dist = length(f - sp);
        float star = smoothstep(0.16 - fi * 0.01, 0.0, dist) * step(0.55, h);
        float tw = 0.7 + 0.3 * sin(t * 0.3 + h * 40.0);
        vec3 lc = mix(vec3(0.05, 0.45, 0.6), vec3(0.75, 0.35, 1.0), fract(fi * 0.37 + 0.15));
        lc = mix(lc, vec3(1.0), step(0.93, h) * 0.6);
        col += star * lc * tw * (0.55 - fi * 0.04);
    }
    col = mix(col, col * vec3(1.5, 1.25, 0.9) + vec3(0.18, 0.1, 0.02), charge * 0.55);
    return col;
}

// Returns the FX colour; alpha <= 0 means the caller discards.
vec4 og_fx(vec4 tex) {
    float t = GameTime * 24000.0; // ticks
    if (ogGui == 1) {
        return tex; // static inventory look
    }
    if (ogFx == 1) {
        // prism core: hue baked in the texture + time, saturated and bright
        float h = fract(og_hue(tex.rgb) + t * 0.02);
        return vec4(og_hsv2rgb(vec3(h, 0.75, 1.0)) * 1.15, tex.a);
    }
    if (ogFx == 2) {
        // prism slash: spectrum sweep + dither dissolve (param.x 0..1)
        if (tex.a < 0.1) {
            return vec4(0.0);
        }
        float fade = ogParam.x;
        if (fade > og_bayer(gl_FragCoord.xy) * 0.98) {
            return vec4(0.0);
        }
        float h = fract(ogLocal.x * 0.8 + ogLocal.y * 0.2 + t * 0.05);
        vec3 c = og_hsv2rgb(vec3(h, 0.6, 1.0));
        return vec4(c * 1.1, tex.a * (1.0 - fade * 0.5));
    }
    if (ogFx == 3) {
        // nova orb: procedural plasma + rim glow, blue -> white with charge
        vec2 p = ogLocal * 6.2831;
        float w = sin(p.x * 1.5 + t * 0.25) + sin(p.y * 2.0 - t * 0.31) + sin((p.x + p.y) * 1.2 + t * 0.17);
        w = w / 3.0 * 0.5 + 0.5;
        float rim = 1.0 - abs(dot(normalize(ogNrmV), normalize(-ogPosV)));
        vec3 cold = vec3(0.25, 0.55, 1.0);
        vec3 hot = vec3(0.95, 0.98, 1.0);
        vec3 c = mix(cold, hot, clamp(w * 0.6 + ogParam.x * 0.6, 0.0, 1.0));
        c += rim * rim * vec3(0.6, 0.8, 1.0);
        float a = clamp(0.55 + 0.45 * w + rim * 0.4, 0.0, 1.0) * tex.a * (1.0 - ogParam.y);
        return vec4(c * (1.2 - 0.5 * ogParam.y), a);
    }
    if (ogFx == 4) {
        // nova ring: band from the texture, dissolves as param.x rises, hue by charge (param.y)
        if (tex.a < 0.1) {
            return vec4(0.0);
        }
        float fade = ogParam.x;
        if (fade > og_bayer(gl_FragCoord.xy) * 0.98) {
            return vec4(0.0);
        }
        vec2 d = ogLocal - 0.5;
        float r = length(d) * 2.0;
        float h = mix(0.58, 0.08, ogParam.y); // blue at low charge -> orange at full
        vec3 c = og_hsv2rgb(vec3(h, 0.5, 1.0));
        float pulse = 0.8 + 0.2 * sin(t * 0.8 + r * 12.0);
        return vec4(c * 1.2 * pulse, tex.a * (1.0 - fade));
    }
    if (ogFx == 5) {
        // tesla bolt: flickering white-blue core, dissolves by param.x
        float fade = ogParam.x;
        if (fade > og_bayer(gl_FragCoord.xy) * 0.98) {
            return vec4(0.0);
        }
        float flick = 0.6 + 0.4 * og_hash(floor(t * 3.0));
        float core = 1.0 - abs(ogLocal.y - 0.5) * 2.0;
        vec3 c = mix(vec3(0.5, 0.7, 1.0), vec3(1.0), core * core);
        return vec4(c * 1.3 * flick, tex.a * flick);
    }
    if (ogFx == 6) {
        // tesla coil orb: crackle pulse with sparse sparks
        float pulse = 0.7 + 0.3 * sin(t * 0.75);
        float cell = floor(ogLocal.x * 8.0) * 7.0 + floor(ogLocal.y * 8.0) * 13.0;
        float spark = step(0.96, og_hash(floor(t * 2.0) + cell));
        vec3 c = tex.rgb * pulse + spark * vec3(0.8, 0.9, 1.0);
        return vec4(c, tex.a);
    }
    if (ogFx == 10) {
        // per-viewer screen overlay. param.x = age/intensity, param.y = variant
        vec2 uv = gl_FragCoord.xy / ScreenSize;
        vec2 cuv = (uv - 0.5) * vec2(ScreenSize.x / ScreenSize.y, 1.0);
        float r = length(cuv);
        float age = ogParam.x;
        int variant = int(ogParam.y * 15.0 + 0.5);
        vec4 o = vec4(0.0);
        if (variant == 0) {
            // shockwave ring expanding from the centre
            float radius = age * 1.3;
            float band = exp(-pow((r - radius) * 14.0, 2.0));
            float inner = smoothstep(radius, radius - 0.25, r) * 0.25;
            o = vec4(mix(vec3(1.0, 0.9, 0.6), vec3(1.0), band), (band * 0.85 + inner) * (1.0 - age));
        } else if (variant == 1) {
            // rainbow vignette sweep
            float ang = atan(cuv.y, cuv.x) / 6.2831;
            vec3 c = og_hsv2rgb(vec3(fract(ang + t * 0.04 + r * 0.5), 0.8, 1.0));
            float vig = smoothstep(0.35, 0.95, r);
            o = vec4(c, vig * 0.65 * (1.0 - age));
        } else if (variant == 2) {
            // charge vignette, intensity = age
            float vig = smoothstep(0.3, 0.9, r);
            float pulse = 0.8 + 0.2 * sin(t * 0.9);
            o = vec4(vec3(0.35, 0.6, 1.0), vig * age * 0.55 * pulse);
        } else if (variant == 3) {
            // glitch: scanline bands with rgb split + red vignette
            float row = floor(uv.y * 48.0);
            float g = og_hash(row * 3.7 + floor(t * 4.0));
            float band = step(0.82, g);
            float stripe = step(0.5, fract(uv.x * 6.0 + (g - 0.5) * 0.8));
            vec3 c = mix(vec3(0.2, 0.9, 1.0), vec3(1.0, 0.2, 0.25), stripe);
            float vig = smoothstep(0.4, 1.0, r) * 0.5;
            o = vec4(mix(vec3(1.0, 0.3, 0.3), c, band), (band * 0.35 + vig) * (1.0 - age));
        } else {
            // white flash
            o = vec4(1.0, 1.0, 1.0, 0.7 * (1.0 - age) * (1.0 - age));
        }
        if (o.a < 0.03) {
            return vec4(0.0); // discard: keeps depth untouched where nothing is drawn
        }
        return o;
    }
    if (ogFx == 11) {
        // gpu sparks: palette by param.y (0 rainbow, 1 plasma, 2 electric), fade by age
        float age = clamp(ogParam.x + fract(t) / 15.0, 0.0, 1.0);
        int pal = int(ogParam.y * 15.0 + 0.5);
        vec3 c;
        if (pal == 0) {
            c = og_hsv2rgb(vec3(fract(ogChain * 8.0 + t * 0.05), 0.8, 1.0));
        } else if (pal == 1) {
            c = mix(vec3(0.4, 0.7, 1.0), vec3(1.0), og_hash(ogChain * 31.0));
        } else {
            c = mix(vec3(0.6, 0.8, 1.0), vec3(1.0), step(0.5, og_hash(floor(t * 2.0) + ogChain * 13.0)));
        }
        float flick = 0.7 + 0.3 * og_hash(floor(t * 2.0) + ogChain * 5.0);
        return vec4(c * 1.4 * flick, (1.0 - age) * (1.0 - age) * tex.a);
    }
    if (ogFx == 15) {
        // tesla sphere: ray-cast like the nova orb; electric cyan starfield, jumping crackle
        // flecks, flickering rim; param.y = zap surge (bigger + whiter for a few ticks)
        vec3 rd = normalize(ogPosV);
        vec3 c = ogCenterV;
        float surge = ogParam.y;
        float r = 0.2 * (1.0 + 0.3 * surge) + 0.012 * sin(t * 0.6);
        float b = dot(rd, c);
        float det = b * b - dot(c, c) + r * r;
        if (det < 0.0) {
            return vec4(0.0);
        }
        float th = b - sqrt(det);
        if (th < 0.05) {
            return vec4(0.0);
        }
        vec3 p = rd * th;
        vec3 n = (p - c) / r;
        vec3 refr = refract(rd, n, 0.74);
        vec3 dw = transpose(mat3(ModelViewMat)) * refr;
        vec3 col = og_portal(dw, t * 1.7, 0.0) * vec3(0.55, 1.0, 1.25);
        float seed = floor(t * 2.5);
        float fleck = step(0.965, og_hash(seed * 3.1 + floor(dot(n, vec3(3.0, 5.0, 7.0)) * 9.0) * 0.37));
        col += fleck * vec3(0.8, 0.95, 1.0) * 1.5;
        float flick = 0.75 + 0.25 * og_hash(seed + 0.5);
        float fres = pow(1.0 - max(dot(n, -rd), 0.0), 2.5);
        col += fres * vec3(0.45, 0.85, 1.0) * 1.4 * flick;
        col += vec3(0.05, 0.12, 0.2) * flick;
        col = mix(col, vec3(1.0), surge * 0.45);
        float a = (0.9 + 0.1 * fres) * (1.0 - ogParam.x);
        return vec4(col, a);
    }
    if (ogFx == 14) {
        // nova sphere: ray-cast a sphere of radius (charge) around the billboard centre;
        // surface = refracted parallax starfield + fresnel rim in the charge colour
        vec3 rd = normalize(ogPosV);
        vec3 c = ogCenterV;
        float r = (0.16 + 0.34 * ogParam.x) * (1.0 - 0.85 * ogParam.y);
        float b = dot(rd, c);
        float det = b * b - dot(c, c) + r * r;
        if (det < 0.0) {
            return vec4(0.0);
        }
        float th = b - sqrt(det);
        if (th < 0.05) {
            return vec4(0.0);
        }
        vec3 p = rd * th;
        vec3 n = (p - c) / r;
        vec3 refr = refract(rd, n, 0.74);
        vec3 dw = transpose(mat3(ModelViewMat)) * refr;
        vec3 col = og_portal(dw, t, ogParam.x);
        float fres = pow(1.0 - max(dot(n, -rd), 0.0), 3.0);
        vec3 rimCol = mix(vec3(0.3, 0.6, 1.0), vec3(1.0, 0.92, 0.7), ogParam.x);
        col += fres * rimCol * 1.3;
        col += (0.15 + 0.25 * ogParam.x) * rimCol * (0.6 + 0.4 * sin(t * 0.5));
        float a = (0.9 + 0.1 * fres) * (1.0 - ogParam.y);
        return vec4(col, a);
    }
    if (ogFx == 12) {
        // blade swing ghost: hue-shifted translucent copy, fades with param.x, hue offset param.y
        float h = fract(og_hue(tex.rgb) + t * 0.03 + ogParam.y * 0.3);
        vec3 c = og_hsv2rgb(vec3(h, 0.55, 1.0));
        float a = tex.a * 0.55 * (1.0 - ogParam.x);
        if (a < 0.02) {
            return vec4(0.0);
        }
        return vec4(c * 1.1, a);
    }
    return tex;
}

// holo edge (FX 13): chromatic split (neighbour samples passed in from main), scanlines, rare flicker
vec4 og_holo(vec4 tex, float rr, float bb) {
    float t = GameTime * 24000.0;
    if (ogGui == 1) {
        return tex;
    }
    vec3 c = vec3(rr, tex.g, bb);
    float scan = 0.88 + 0.12 * sin(gl_FragCoord.y * 1.7 + t * 1.5);
    float flick = 1.0 - 0.25 * step(0.985, og_hash(floor(t * 1.5)));
    return vec4(c * 1.12 * scan * flick, tex.a);
}
// ---- end OrangeGames FX decl ----
"""

FSH_MAIN_HEAD = """
    // ---- OrangeGames FX ----
    if (ogFx != 0) {
        vec4 ogTex = texture(Sampler0, texCoord0);
        vec4 ogC;
        if (ogFx == 13) {
            vec2 ogPx = 1.0 / vec2(textureSize(Sampler0, 0));
            float ogOff = 0.6 + 0.6 * sin(GameTime * 24000.0 * 0.7);
            ogC = og_holo(ogTex,
                          texture(Sampler0, texCoord0 + vec2(ogPx.x * ogOff, 0.0)).r,
                          texture(Sampler0, texCoord0 - vec2(ogPx.x * ogOff, 0.0)).b);
        } else {
            ogC = og_fx(ogTex);
        }
        if (ogC.a <= 0.0) {
            discard;
        }
        ogC *= ColorModulator;
%%OVERLAY%%
        fragColor = apply_fog(ogC, sphericalVertexDistance, cylindricalVertexDistance, FogEnvironmentalStart, FogEnvironmentalEnd, FogRenderDistanceStart, FogRenderDistanceEnd, FogColor);
        return;
    }
    // ---- end OrangeGames FX ----
"""


def inject(text, anchor, block, what):
    i = text.find(anchor)
    if i < 0:
        sys.exit(f"anchor not found ({what}): {anchor!r}")
    if text.find(anchor, i + 1) >= 0:
        sys.exit(f"anchor not unique ({what}): {anchor!r}")
    j = i + len(anchor)
    return text[:j] + block + text[j:]


def check(ver, name, text):
    if text.count("{") != text.count("}"):
        sys.exit(f"{ver} {name}: unbalanced braces")
    if text.count("#if") != text.count("#endif"):
        sys.exit(f"{ver} {name}: unbalanced preprocessor")


def gen(ver, src_dir, base):
    src = REPO / "tools" / "vanilla_shaders" / src_dir
    dst = REPO / f"ogfx_{ver}/assets/minecraft/shaders/core"
    dst.mkdir(parents=True, exist_ok=True)
    vsh = (src / f"{base}.vsh").read_text(encoding="utf-8")
    fsh = (src / f"{base}.fsh").read_text(encoding="utf-8")

    vsh = inject(vsh, "#moj_import <minecraft:projection.glsl>\n", VSH_DECL, f"{ver} vsh decl")
    vcolor = "        vertexColor = vec4(1.0);"
    if "out vec4 lightMapColor;" in vsh:
        vcolor += "\n        lightMapColor = vec4(1.0);"
    tail = VSH_MAIN_TAIL.replace("%%VERTEX_COLOR%%", vcolor)
    last = vsh.rstrip().rfind("}")
    vsh = vsh[:last] + tail + vsh[last:]
    for must in ("vertexColor", "Position", "Normal", "UV2", "ProjMat", "ModelViewMat", "in vec4 Color;"):
        if must not in vsh:
            sys.exit(f"{ver} vsh: expected symbol {must} missing")

    fsh = inject(fsh, "#moj_import <minecraft:dynamictransforms.glsl>\n", FSH_DECL, f"{ver} fsh decl")
    overlay = ("        ogC.rgb = mix(overlayColor.rgb, ogC.rgb, overlayColor.a);"
               if "in vec4 overlayColor;" in fsh else "")
    head = FSH_MAIN_HEAD.replace("%%OVERLAY%%", overlay)
    fsh = inject(fsh, "void main() {\n", head, f"{ver} fsh main")
    for must in ("apply_fog(", "uniform sampler2D Sampler0;", "in vec2 texCoord0;"):
        if must not in fsh:
            sys.exit(f"{ver} fsh: expected symbol {must} missing")

    check(ver, "vsh", vsh)
    check(ver, "fsh", fsh)
    (dst / f"{base}.vsh").write_text(vsh, encoding="utf-8", newline="\n")
    (dst / f"{base}.fsh").write_text(fsh, encoding="utf-8", newline="\n")
    print(f"ogfx_{ver}: ok ({base})")


if __name__ == "__main__":
    for v, (src_dir, base) in VERSIONS.items():
        gen(v, src_dir, base)
