#!/usr/bin/env python3
"""Merge OrangeGames FX blocks into ModelEngine's vendored core/entity shaders.

Writes ogfx_<ver>/assets/minecraft/shaders/core/entity.{vsh,fsh} for every
version family that has the Globals UBO (GameTime), i.e. 1.21.6+. Rerun
whenever a modelengine_* overlay is re-vendored. pack.mcmeta must list the
ogfx_* overlays AFTER the modelengine_* ones (last overlay wins).

Anchors are exact substrings present in all supported ME versions; the script
exits non-zero if one is missing or ambiguous so a silent no-FX pack can never
ship. ModelEngine's own text is left byte-identical apart from the inserted
blocks, which are delimited by "OrangeGames FX" comments.

Marker convention (shared with tools/gen_fx_art.py):
    vertex Color == (255, 254 - sub, FXID)/255   sub = 0..14 sub-index
    FX ids: 1 prism core, 2 prism slash, 3 nova orb, 4 nova ring,
            5 tesla bolt, 6 tesla coil orb
Per-entity parameters ride in UV2 (ItemDisplay brightness): block light ->
ogParam.x, sky light -> ogParam.y, each 0..1 in 1/15 steps.
"""
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
VERSIONS = ["1_21_6", "26_1", "26_2"]

VSH_DECL = """
// ---- OrangeGames FX (generated by tools/gen_fx_shaders.py) ----
#moj_import <minecraft:globals.glsl>
flat out int ogFx;
flat out int ogGui;
out vec2 ogLocal;
out vec2 ogParam;
out float ogChain;
out vec3 ogNrmV;
out vec3 ogPosV;
// ---- end OrangeGames FX decl ----
"""

VSH_MAIN_TAIL = """
    // ---- OrangeGames FX ----
    ogFx = 0;
    ogGui = (abs(ProjMat[2][3]) < 10e-6) ? 1 : 0;
    int ogCorner = gl_VertexID % 4;
    ogLocal = vec2(ogCorner >= 2 ? 1.0 : 0.0, (ogCorner == 1 || ogCorner == 2) ? 1.0 : 0.0);
    ogChain = ogLocal.x;
    ogParam = vec2(float(UV2.x >> 4), float(UV2.y >> 4)) / 15.0;
    ogNrmV = normalize((ModelViewMat * vec4(Normal, 0.0)).xyz);
    ogPosV = (ModelViewMat * vec4(Position, 1.0)).xyz;
    float ogG = Color.g * 255.0;
    if (Color.r > 0.999 && ogG > 239.5 && ogG < 254.5) {
        ogFx = int(Color.b * 255.0 + 0.5);
        float ogSub = 254.0 - floor(ogG + 0.5);
        ogChain = (ogSub + ogLocal.x) / 8.0;
        float ogT = GameTime * 24000.0; // ticks, fractional
#ifdef PER_FACE_LIGHTING
        vertexPerFaceColorBack = vec4(1.0);
        vertexPerFaceColorFront = vec4(1.0);
#else
        vertexColor = vec4(1.0);
#endif
#ifndef EMISSIVE
        lightMapColor = vec4(1.0);
#endif
        if (ogGui == 0) {
            vec3 ogDisp = vec3(0.0);
            if (ogFx == 3) {
                // nova orb: breathing pulse along the normal, stronger with charge
                ogDisp = Normal * (0.02 + 0.05 * ogParam.x) * sin(ogT * 0.9 + ogLocal.x * 6.2831 + ogLocal.y * 3.1);
            } else if (ogFx == 5) {
                // tesla bolt: per-frame jitter, pinned at both ends of the chain
                float ogSeed = floor(ogT * 3.0) * 17.0 + ogSub * 5.0 + float(ogCorner >= 2 ? 1 : 0) * 3.0;
                vec3 ogH = fract(sin(vec3(ogSeed * 12.9898, ogSeed * 78.233, ogSeed * 37.719)) * 43758.5453) - 0.5;
                ogDisp = ogH * 0.45 * sin(3.14159 * ogChain);
            }
            if (ogFx == 3 || ogFx == 5) {
                gl_Position = ProjMat * ModelViewMat * vec4(Position + ogDisp, 1.0);
            }
        }
    }
    // ---- end OrangeGames FX ----
"""

FSH_DECL = """
// ---- OrangeGames FX (generated by tools/gen_fx_shaders.py) ----
#moj_import <minecraft:globals.glsl>
flat in int ogFx;
flat in int ogGui;
in vec2 ogLocal;
in vec2 ogParam;
in float ogChain;
in vec3 ogNrmV;
in vec3 ogPosV;

vec3 og_hsv2rgb(vec3 c) {
    vec3 p = abs(fract(c.xxx + vec3(0.0, 2.0 / 3.0, 1.0 / 3.0)) * 6.0 - 3.0);
    return c.z * mix(vec3(1.0), clamp(p - 1.0, 0.0, 1.0), c.y);
}

float og_hue(vec3 c) {
    float mx = max(c.r, max(c.g, c.b));
    float mn = min(c.r, min(c.g, c.b));
    float d = mx - mn;
    if (d < 1e-4) {
        return 0.0;
    }
    float h;
    if (mx == c.r) {
        h = mod((c.g - c.b) / d, 6.0);
    } else if (mx == c.g) {
        h = (c.b - c.r) / d + 2.0;
    } else {
        h = (c.r - c.g) / d + 4.0;
    }
    return h / 6.0;
}

float og_bayer(vec2 p) {
    int x = int(mod(p.x, 4.0));
    int y = int(mod(p.y, 4.0));
    int i = x + y * 4;
    float v = 0.0;
    if (i == 0) v = 0.0; else if (i == 1) v = 8.0; else if (i == 2) v = 2.0; else if (i == 3) v = 10.0;
    else if (i == 4) v = 12.0; else if (i == 5) v = 4.0; else if (i == 6) v = 14.0; else if (i == 7) v = 6.0;
    else if (i == 8) v = 3.0; else if (i == 9) v = 11.0; else if (i == 10) v = 1.0; else if (i == 11) v = 9.0;
    else if (i == 12) v = 15.0; else if (i == 13) v = 7.0; else if (i == 14) v = 13.0; else v = 5.0;
    return (v + 0.5) / 16.0;
}

float og_hash(float n) {
    return fract(sin(n) * 43758.5453);
}

// Returns the FX colour; alpha <= 0 means the caller discards.
vec4 og_fx(vec4 tex) {
    float t = GameTime * 24000.0; // ticks
    if (ogGui == 1) {
        return tex; // static inventory look
    }
    if (ogFx == 1) {
        // prism core: hue baked in the texture + time, saturated and bright
        float h = fract(og_hue(tex.rgb) + t * 0.02);
        return vec4(og_hsv2rgb(vec3(h, 0.75, 1.0)) * 1.15, tex.a);
    }
    if (ogFx == 2) {
        // prism slash: spectrum sweep + dither dissolve (param.x 0..1)
        if (tex.a < 0.1) {
            return vec4(0.0);
        }
        float fade = ogParam.x;
        if (fade > og_bayer(gl_FragCoord.xy) * 0.98) {
            return vec4(0.0);
        }
        float h = fract(ogLocal.x * 0.8 + ogLocal.y * 0.2 + t * 0.05);
        vec3 c = og_hsv2rgb(vec3(h, 0.6, 1.0));
        return vec4(c * 1.1, tex.a * (1.0 - fade * 0.5));
    }
    if (ogFx == 3) {
        // nova orb: procedural plasma + rim glow, blue -> white with charge
        vec2 p = ogLocal * 6.2831;
        float w = sin(p.x * 1.5 + t * 0.25) + sin(p.y * 2.0 - t * 0.31) + sin((p.x + p.y) * 1.2 + t * 0.17);
        w = w / 3.0 * 0.5 + 0.5;
        float rim = 1.0 - abs(dot(normalize(ogNrmV), normalize(-ogPosV)));
        vec3 cold = vec3(0.25, 0.55, 1.0);
        vec3 hot = vec3(0.95, 0.98, 1.0);
        vec3 c = mix(cold, hot, clamp(w * 0.6 + ogParam.x * 0.6, 0.0, 1.0));
        c += rim * rim * vec3(0.6, 0.8, 1.0);
        float a = clamp(0.55 + 0.45 * w + rim * 0.4, 0.0, 1.0) * tex.a;
        return vec4(c * 1.2, a);
    }
    if (ogFx == 4) {
        // nova ring: band from the texture, dissolves as param.x rises, hue by charge (param.y)
        if (tex.a < 0.1) {
            return vec4(0.0);
        }
        float fade = ogParam.x;
        if (fade > og_bayer(gl_FragCoord.xy) * 0.98) {
            return vec4(0.0);
        }
        vec2 d = ogLocal - 0.5;
        float r = length(d) * 2.0;
        float h = mix(0.58, 0.08, ogParam.y); // blue at low charge -> orange at full
        vec3 c = og_hsv2rgb(vec3(h, 0.5, 1.0));
        float pulse = 0.8 + 0.2 * sin(t * 0.8 + r * 12.0);
        return vec4(c * 1.2 * pulse, tex.a * (1.0 - fade));
    }
    if (ogFx == 5) {
        // tesla bolt: flickering white-blue core, dissolves by param.x
        float fade = ogParam.x;
        if (fade > og_bayer(gl_FragCoord.xy) * 0.98) {
            return vec4(0.0);
        }
        float flick = 0.6 + 0.4 * og_hash(floor(t * 3.0));
        float core = 1.0 - abs(ogLocal.y - 0.5) * 2.0;
        vec3 c = mix(vec3(0.5, 0.7, 1.0), vec3(1.0), core * core);
        return vec4(c * 1.3 * flick, tex.a * flick);
    }
    if (ogFx == 6) {
        // tesla coil orb: crackle pulse with sparse sparks
        float pulse = 0.7 + 0.3 * sin(t * 0.75);
        float cell = floor(ogLocal.x * 8.0) * 7.0 + floor(ogLocal.y * 8.0) * 13.0;
        float spark = step(0.96, og_hash(floor(t * 2.0) + cell));
        vec3 c = tex.rgb * pulse + spark * vec3(0.8, 0.9, 1.0);
        return vec4(c, tex.a);
    }
    return tex;
}
// ---- end OrangeGames FX decl ----
"""

FSH_MAIN_HEAD = """
    // ---- OrangeGames FX ----
    if (ogFx != 0) {
        vec4 ogC = og_fx(color);
        if (ogC.a <= 0.0) {
            discard;
        }
        ogC *= ColorModulator;
#ifndef NO_OVERLAY
        ogC.rgb = mix(overlayColor.rgb, ogC.rgb, overlayColor.a);
#endif
        fragColor = apply_fog(ogC, sphericalVertexDistance, cylindricalVertexDistance, FogEnvironmentalStart, FogEnvironmentalEnd, FogRenderDistanceStart, FogRenderDistanceEnd, FogColor);
        return;
    }
    // ---- end OrangeGames FX ----
"""


def inject(text, anchor, block, what):
    i = text.find(anchor)
    if i < 0:
        sys.exit(f"anchor not found ({what}): {anchor!r}")
    if text.find(anchor, i + 1) >= 0:
        sys.exit(f"anchor not unique ({what}): {anchor!r}")
    j = i + len(anchor)
    return text[:j] + block + text[j:]


def check(ver, name, text):
    if text.count("{") != text.count("}"):
        sys.exit(f"{ver} {name}: unbalanced braces")
    if text.count("#if") != text.count("#endif"):
        sys.exit(f"{ver} {name}: unbalanced preprocessor")


def gen(ver):
    src = REPO / f"modelengine_{ver}/assets/minecraft/shaders/core"
    dst = REPO / f"ogfx_{ver}/assets/minecraft/shaders/core"
    dst.mkdir(parents=True, exist_ok=True)
    vsh = (src / "entity.vsh").read_text(encoding="utf-8")
    fsh = (src / "entity.fsh").read_text(encoding="utf-8")

    vsh = inject(vsh, "#moj_import <minecraft:projection.glsl>\n", VSH_DECL, f"{ver} vsh decl")
    last = vsh.rstrip().rfind("}")
    vsh = vsh[:last] + VSH_MAIN_TAIL + vsh[last:]
    for must in ("vertexColor", "Position", "Normal", "UV2", "ProjMat", "ModelViewMat"):
        if must not in vsh:
            sys.exit(f"{ver} vsh: expected symbol {must} missing")

    fsh = inject(fsh, "#moj_import <minecraft:dynamictransforms.glsl>\n", FSH_DECL, f"{ver} fsh decl")
    fsh = inject(fsh, "vec4 color = texture(Sampler0, texCoord0);\n", FSH_MAIN_HEAD, f"{ver} fsh main")
    if "apply_fog(" not in fsh.split("// ---- OrangeGames FX ----")[0] + fsh.split("// ---- end OrangeGames FX ----")[-1]:
        sys.exit(f"{ver} fsh: ME source does not use apply_fog; signature assumption broken")

    check(ver, "vsh", vsh)
    check(ver, "fsh", fsh)
    (dst / "entity.vsh").write_text(vsh, encoding="utf-8", newline="\n")
    (dst / "entity.fsh").write_text(fsh, encoding="utf-8", newline="\n")
    print(f"ogfx_{ver}: ok")


if __name__ == "__main__":
    for v in VERSIONS:
        gen(v)
