#version 330

#moj_import <minecraft:light.glsl>
#moj_import <minecraft:fog.glsl>
#moj_import <minecraft:dynamictransforms.glsl>
#moj_import <minecraft:projection.glsl>

// ---- OrangeGames FX (generated by tools/gen_fx_shaders.py) ----
#moj_import <minecraft:globals.glsl>
flat out int ogFx;
flat out int ogGui;
flat out int ogSubI;
out vec2 ogLocal;
out vec2 ogLocalB;
out vec2 ogParam;
out float ogChain;
out vec3 ogNrmV;
out vec3 ogPosV;
out vec3 ogCenterV;
// ---- end OrangeGames FX decl ----
#moj_import <minecraft:sample_lightmap.glsl>

in vec3 Position;
in vec4 Color;
in vec2 UV0;
in ivec2 UV1;
in ivec2 UV2;
in vec3 Normal;

uniform sampler2D Sampler2;

out float sphericalVertexDistance;
out float cylindricalVertexDistance;
out vec4 vertexColor;
out vec2 texCoord0;

void main() {
    gl_Position = ProjMat * ModelViewMat * vec4(Position, 1.0);

    sphericalVertexDistance = fog_spherical_distance(Position);
    cylindricalVertexDistance = fog_cylindrical_distance(Position);

    vertexColor = minecraft_mix_light(Light0_Direction, Light1_Direction, Normal, Color) * sample_lightmap(Sampler2, UV2);

    texCoord0 = UV0;

    // ---- OrangeGames FX ----
    ogFx = 0;
    ogGui = (abs(ProjMat[2][3]) < 10e-6) ? 1 : 0;
    int ogCorner = gl_VertexID % 4;
    ogLocal = vec2(ogCorner >= 2 ? 1.0 : 0.0, (ogCorner == 1 || ogCorner == 2) ? 1.0 : 0.0);
    // second candidate labelling: quads expanded to two triangles (v0,v1,v2, v2,v3,v0) with no
    // index buffer - pipeline-replacing clients do this and it shears the %4 labels on tri 2
    int ogC6 = gl_VertexID % 6;
    int ogCornerB = ogC6 < 3 ? ogC6 : (ogC6 == 3 ? 2 : (ogC6 == 4 ? 3 : 0));
    ogLocalB = vec2(ogCornerB >= 2 ? 1.0 : 0.0, (ogCornerB == 1 || ogCornerB == 2) ? 1.0 : 0.0);
    ogChain = ogLocal.x;
    ogParam = vec2(float(UV2.x >> 4), float(UV2.y >> 4)) / 15.0;
    ogNrmV = normalize((ModelViewMat * vec4(Normal, 0.0)).xyz);
    ogPosV = (ModelViewMat * vec4(Position, 1.0)).xyz;
    ogCenterV = ogPosV;
    ogSubI = 0;
    float ogG = Color.g * 255.0;
    float ogB = Color.b * 255.0;
    if (Color.r > 0.999 && ogG > 199.5 && ogG < 254.5 && ogB > 223.5 && ogB < 254.5) {
        ogFx = 255 - int(ogB + 0.5);
        float ogSub = 254.0 - floor(ogG + 0.5);
        ogSubI = int(ogSub + 0.5);
        ogChain = (ogSub + ogLocal.x) / 8.0;
        float ogT = GameTime * 24000.0; // ticks, fractional
        vertexColor = vec4(1.0);
        if (ogGui == 0) {
            vec3 ogDisp = vec3(0.0);
            if (ogFx == 3) {
                // nova orb: breathing pulse along the normal, stronger with charge
                ogDisp = Normal * (0.02 + 0.05 * ogParam.x) * sin(ogT * 0.9 + ogLocal.x * 6.2831 + ogLocal.y * 3.1);
            } else if (ogFx == 5) {
                // tesla bolt: per-frame jitter, pinned at both ends of the chain
                float ogSeed = floor(ogT * 3.0) * 17.0 + ogSub * 5.0 + float(ogCorner >= 2 ? 1 : 0) * 3.0 + ogParam.y * 97.0;
                vec3 ogH = fract(sin(vec3(ogSeed * 12.9898, ogSeed * 78.233, ogSeed * 37.719)) * 43758.5453) - 0.5;
                ogDisp = ogH * 0.45 * sin(3.14159 * ogChain);
            }
            if (ogFx == 3 || ogFx == 5) {
                gl_Position = ProjMat * ModelViewMat * vec4(Position + ogDisp, 1.0);
            }
            if (ogFx == 11) {
                // gpu sparks: every micro-cube (sub-index) flies its own hashed trajectory;
                // age = coarse per-tick param + sub-tick smoothing from GameTime
                float ogAge = clamp(ogParam.x + fract(ogT) / 15.0, 0.0, 1.0);
                vec3 ogHs = fract(sin(vec3(ogSub * 12.9898 + 1.0, ogSub * 78.233 + 2.0, ogSub * 37.719 + 3.0)) * 43758.5453);
                vec3 ogDir = normalize(ogHs - 0.5 + vec3(0.0, 0.15, 0.0));
                float ogSpd = 0.8 + fract(ogHs.x * 7.13) * 1.6;
                float ogEase = 1.0 - (1.0 - ogAge) * (1.0 - ogAge);
                vec3 ogFly = ogDir * ogSpd * ogEase * 2.2 + vec3(0.0, -1.6 * ogAge * ogAge, 0.0);
                gl_Position = ProjMat * ModelViewMat * vec4(Position + ogFly, 1.0);
            }
        }
        if (ogFx == 10) {
            // screen overlay: pin the quad just past the near plane, spanning the view
            if (ogGui == 0) {
                gl_Position = ProjMat * vec4((ogLocal.x * 2.0 - 1.0) * 0.32, (1.0 - ogLocal.y * 2.0) * 0.32, -0.06, 1.0);
            } else {
                gl_Position = vec4(0.0, 0.0, 0.0, 1.0); // degenerate: never drawn in inventories
            }
        }
    }
    // ---- end OrangeGames FX ----
}
