#version 150

#moj_import <minecraft:fog.glsl>
#moj_import <minecraft:dynamictransforms.glsl>

// ---- OrangeGames FX (generated by tools/gen_fx_shaders.py) ----
#moj_import <minecraft:globals.glsl>
flat in int ogFx;
flat in int ogGui;
flat in int ogSubI;
in vec2 ogLocal;
in vec2 ogParam;
in float ogChain;
in vec3 ogNrmV;
in vec3 ogPosV;
in vec3 ogCenterV;

vec3 og_hsv2rgb(vec3 c) {
    vec3 p = abs(fract(c.xxx + vec3(0.0, 2.0 / 3.0, 1.0 / 3.0)) * 6.0 - 3.0);
    return c.z * mix(vec3(1.0), clamp(p - 1.0, 0.0, 1.0), c.y);
}

float og_hue(vec3 c) {
    float mx = max(c.r, max(c.g, c.b));
    float mn = min(c.r, min(c.g, c.b));
    float d = mx - mn;
    if (d < 1e-4) {
        return 0.0;
    }
    float h;
    if (mx == c.r) {
        h = mod((c.g - c.b) / d, 6.0);
    } else if (mx == c.g) {
        h = (c.b - c.r) / d + 2.0;
    } else {
        h = (c.r - c.g) / d + 4.0;
    }
    return h / 6.0;
}

float og_bayer(vec2 p) {
    int x = int(mod(p.x, 4.0));
    int y = int(mod(p.y, 4.0));
    int i = x + y * 4;
    float v = 0.0;
    if (i == 0) v = 0.0; else if (i == 1) v = 8.0; else if (i == 2) v = 2.0; else if (i == 3) v = 10.0;
    else if (i == 4) v = 12.0; else if (i == 5) v = 4.0; else if (i == 6) v = 14.0; else if (i == 7) v = 6.0;
    else if (i == 8) v = 3.0; else if (i == 9) v = 11.0; else if (i == 10) v = 1.0; else if (i == 11) v = 9.0;
    else if (i == 12) v = 15.0; else if (i == 13) v = 7.0; else if (i == 14) v = 13.0; else v = 5.0;
    return (v + 0.5) / 16.0;
}

float og_hash(float n) {
    return fract(sin(n) * 43758.5453);
}

vec3 og_rotY(vec3 v, float a) {
    float c = cos(a);
    float s = sin(a);
    return vec3(c * v.x + s * v.z, v.y, -s * v.x + c * v.z);
}

vec3 og_rotX(vec3 v, float a) {
    float c = cos(a);
    float s = sin(a);
    return vec3(v.x, c * v.y - s * v.z, s * v.y + c * v.z);
}

// End-portal style parallax starfield looked up by world-space direction: eight
// layers of hashed specks, each rotating at its own speed, teal -> violet, over
// deep space. charge warms the field toward white-gold.
vec3 og_portal(vec3 dir, float t, float charge) {
    vec3 col = vec3(0.015, 0.01, 0.05);
    for (int i = 0; i < 8; i++) {
        float fi = float(i);
        vec3 d = og_rotY(dir, t * (0.004 + 0.0025 * fi) + fi * 0.9);
        d = og_rotX(d, fi * 0.55 + t * 0.0015 * fi);
        vec2 uv = vec2(atan(d.z, d.x), asin(clamp(d.y, -1.0, 1.0))) * (2.5 + fi * 1.3);
        vec2 cell = floor(uv);
        vec2 f = fract(uv) - 0.5;
        float h = og_hash(dot(cell, vec2(127.1, 311.7)) + fi * 19.19);
        vec2 sp = (vec2(og_hash(h * 7.0), og_hash(h * 13.0)) - 0.5) * 0.8;
        float dist = length(f - sp);
        float star = smoothstep(0.16 - fi * 0.01, 0.0, dist) * step(0.55, h);
        float tw = 0.7 + 0.3 * sin(t * 0.3 + h * 40.0);
        vec3 lc = mix(vec3(0.05, 0.45, 0.6), vec3(0.75, 0.35, 1.0), fract(fi * 0.37 + 0.15));
        lc = mix(lc, vec3(1.0), step(0.93, h) * 0.6);
        col += star * lc * tw * (0.55 - fi * 0.04);
    }
    col = mix(col, col * vec3(1.5, 1.25, 0.9) + vec3(0.18, 0.1, 0.02), charge * 0.55);
    return col;
}

// Distance from the view ray (origin, direction rd) to the segment qa-qb.
float og_ray_seg(vec3 rd, vec3 qa, vec3 qb) {
    vec3 v = qb - qa;
    float a = dot(rd, rd);
    float b = dot(rd, v);
    float c = dot(v, v);
    float d = dot(rd, -qa);
    float e = dot(v, -qa);
    float den = a * c - b * b;
    float tt = den > 1e-6 ? clamp((a * e - b * d) / den, 0.0, 1.0) : 0.0;
    vec3 q = qa + v * tt;
    float s = max(dot(q, rd) / a, 0.0);
    return length(rd * s - q);
}

float og_hexdist(vec2 p) {
    p = abs(p);
    return max(dot(p, normalize(vec2(1.0, 1.73))), p.x);
}

// x,y = cell-local polar angle / distance-to-edge (0 at edges, 0.5 at centre), zw = cell id
vec4 og_hexcoords(vec2 uv) {
    vec2 r = vec2(1.0, 1.73);
    vec2 h = r * 0.5;
    vec2 a = mod(uv, r) - h;
    vec2 b = mod(uv - h, r) - h;
    vec2 gv = dot(a, a) < dot(b, b) ? a : b;
    float x = atan(gv.x, gv.y);
    float y = 0.5 - og_hexdist(gv);
    vec2 id = uv - gv;
    return vec4(x, y, id.x, id.y);
}

// Returns the FX colour; alpha <= 0 means the caller discards.
vec4 og_fx(vec4 tex) {
    float t = GameTime * 24000.0; // ticks
    if (ogGui == 1) {
        return tex; // static inventory look
    }
    if (ogFx == 1) {
        // prism core: hue baked in the texture + time, saturated and bright
        float h = fract(og_hue(tex.rgb) + t * 0.02);
        return vec4(og_hsv2rgb(vec3(h, 0.75, 1.0)) * 1.15, tex.a);
    }
    if (ogFx == 2) {
        // prism slash: spectrum sweep + dither dissolve (param.x 0..1)
        if (tex.a < 0.1) {
            return vec4(0.0);
        }
        float fade = ogParam.x;
        if (fade > og_bayer(gl_FragCoord.xy) * 0.98) {
            return vec4(0.0);
        }
        float h = fract(ogLocal.x * 0.8 + ogLocal.y * 0.2 + t * 0.05);
        vec3 c = og_hsv2rgb(vec3(h, 0.6, 1.0));
        return vec4(c * 1.1, tex.a * (1.0 - fade * 0.5));
    }
    if (ogFx == 3) {
        // nova orb: procedural plasma + rim glow, blue -> white with charge
        vec2 p = ogLocal * 6.2831;
        float w = sin(p.x * 1.5 + t * 0.25) + sin(p.y * 2.0 - t * 0.31) + sin((p.x + p.y) * 1.2 + t * 0.17);
        w = w / 3.0 * 0.5 + 0.5;
        float rim = 1.0 - abs(dot(normalize(ogNrmV), normalize(-ogPosV)));
        vec3 cold = vec3(0.25, 0.55, 1.0);
        vec3 hot = vec3(0.95, 0.98, 1.0);
        vec3 c = mix(cold, hot, clamp(w * 0.6 + ogParam.x * 0.6, 0.0, 1.0));
        c += rim * rim * vec3(0.6, 0.8, 1.0);
        float a = clamp(0.55 + 0.45 * w + rim * 0.4, 0.0, 1.0) * tex.a * (1.0 - ogParam.y);
        return vec4(c * (1.2 - 0.5 * ogParam.y), a);
    }
    if (ogFx == 4) {
        // nova ring: band from the texture, dissolves as param.x rises, hue by charge (param.y)
        if (tex.a < 0.1) {
            return vec4(0.0);
        }
        float fade = ogParam.x;
        if (fade > og_bayer(gl_FragCoord.xy) * 0.98) {
            return vec4(0.0);
        }
        vec2 d = ogLocal - 0.5;
        float r = length(d) * 2.0;
        if (ogSubI == 1) {
            // accretion disc: spinning streaks, doppler-shifted (blue approaching, red receding)
            float ang = atan(d.y, d.x) + t * 0.25;
            float dop = sin(ang) * 0.5 + 0.5;
            vec3 cA = mix(vec3(1.0, 0.35, 0.2), vec3(0.45, 0.7, 1.0), dop);
            float streaks = 0.7 + 0.3 * sin(ang * 9.0 + r * 22.0 - t * 0.6);
            return vec4(cA * 1.5 * streaks, tex.a * (1.0 - fade) * (0.45 + 0.55 * streaks));
        }
        float h = mix(0.58, 0.08, ogParam.y); // blue at low charge -> orange at full
        vec3 c = og_hsv2rgb(vec3(h, 0.5, 1.0));
        float pulse = 0.8 + 0.2 * sin(t * 0.8 + r * 12.0);
        return vec4(c * 1.2 * pulse, tex.a * (1.0 - fade));
    }
    if (ogFx == 5) {
        // tesla bolt: flickering white-blue core, dissolves by param.x
        float fade = ogParam.x;
        if (fade > og_bayer(gl_FragCoord.xy) * 0.98) {
            return vec4(0.0);
        }
        float flick = 0.6 + 0.4 * og_hash(floor(t * 3.0));
        float core = 1.0 - abs(ogLocal.y - 0.5) * 2.0;
        vec3 c = mix(vec3(0.5, 0.7, 1.0), vec3(1.0), core * core);
        return vec4(c * 1.3 * flick, tex.a * flick);
    }
    if (ogFx == 6) {
        // tesla coil orb: crackle pulse with sparse sparks
        float pulse = 0.7 + 0.3 * sin(t * 0.75);
        float cell = floor(ogLocal.x * 8.0) * 7.0 + floor(ogLocal.y * 8.0) * 13.0;
        float spark = step(0.96, og_hash(floor(t * 2.0) + cell));
        vec3 c = tex.rgb * pulse + spark * vec3(0.8, 0.9, 1.0);
        return vec4(c, tex.a);
    }
    if (ogFx == 10) {
        // per-viewer screen overlay. param.x = age/intensity, param.y = variant
        vec2 uv = gl_FragCoord.xy / ScreenSize;
        vec2 cuv = (uv - 0.5) * vec2(ScreenSize.x / ScreenSize.y, 1.0);
        float r = length(cuv);
        float age = ogParam.x;
        int variant = int(ogParam.y * 15.0 + 0.5);
        vec4 o = vec4(0.0);
        if (variant == 0) {
            // shockwave ring expanding from the centre
            float radius = age * 1.3;
            float band = exp(-pow((r - radius) * 14.0, 2.0));
            float inner = smoothstep(radius, radius - 0.25, r) * 0.25;
            o = vec4(mix(vec3(1.0, 0.9, 0.6), vec3(1.0), band), (band * 0.85 + inner) * (1.0 - age));
        } else if (variant == 1) {
            // rainbow vignette sweep
            float ang = atan(cuv.y, cuv.x) / 6.2831;
            vec3 c = og_hsv2rgb(vec3(fract(ang + t * 0.04 + r * 0.5), 0.8, 1.0));
            float vig = smoothstep(0.35, 0.95, r);
            o = vec4(c, vig * 0.65 * (1.0 - age));
        } else if (variant == 2) {
            // charge vignette, intensity = age
            float vig = smoothstep(0.3, 0.9, r);
            float pulse = 0.8 + 0.2 * sin(t * 0.9);
            o = vec4(vec3(0.35, 0.6, 1.0), vig * age * 0.55 * pulse);
        } else if (variant == 3) {
            // glitch: scanline bands with rgb split + red vignette
            float row = floor(uv.y * 48.0);
            float g = og_hash(row * 3.7 + floor(t * 4.0));
            float band = step(0.82, g);
            float stripe = step(0.5, fract(uv.x * 6.0 + (g - 0.5) * 0.8));
            vec3 c = mix(vec3(0.2, 0.9, 1.0), vec3(1.0, 0.2, 0.25), stripe);
            float vig = smoothstep(0.4, 1.0, r) * 0.5;
            o = vec4(mix(vec3(1.0, 0.3, 0.3), c, band), (band * 0.35 + vig) * (1.0 - age));
        } else if (variant == 5) {
            // chrono: cool vignette, sweeping clock hand, faint scanlines
            float ang = fract(atan(cuv.y, cuv.x) / 6.2831 - t * 0.02);
            float hand = smoothstep(0.05, 0.0, ang) * smoothstep(0.02, 0.08, r) * (1.0 - smoothstep(0.45, 0.6, r));
            float vig = smoothstep(0.35, 1.0, r);
            float scan = 0.5 + 0.5 * sin(gl_FragCoord.y * 1.2 + t);
            o = vec4(vec3(0.55, 0.8, 1.0), (vig * 0.45 + hand * 0.6 + vig * scan * 0.08) * (1.0 - age));
        } else if (variant == 6) {
            // void pull: violet vignette breathing inward
            float pulse = 0.8 + 0.2 * sin(t * 0.6);
            float vig = smoothstep(0.25 * pulse, 0.95, r);
            o = vec4(vec3(0.45, 0.2, 0.8), vig * 0.6 * (1.0 - age));
        } else if (variant == 7) {
            // implosion: ring contracting to the centre, then a violet-white pop
            float radius = (1.0 - age) * 1.2;
            float band = exp(-pow((r - radius) * 12.0, 2.0));
            float pop = smoothstep(0.7, 1.0, age) * smoothstep(0.5, 0.0, r);
            o = vec4(mix(vec3(0.7, 0.4, 1.0), vec3(1.0), pop), band * 0.8 + pop * 0.8 * (1.0 - age));
        } else if (variant == 8) {
            // quake: orange flash + horizontal jitter bands
            float band = step(0.9, og_hash(floor(uv.y * 30.0) + floor(t * 6.0)));
            float vig = smoothstep(0.2, 1.0, r);
            o = vec4(vec3(1.0, 0.6, 0.25), 0.35 * (1.0 - age) * (1.0 - age) + vig * 0.4 * (1.0 - age) + band * 0.25 * (1.0 - age));
        } else {
            // white flash
            o = vec4(1.0, 1.0, 1.0, 0.7 * (1.0 - age) * (1.0 - age));
        }
        if (o.a < 0.03) {
            return vec4(0.0); // discard: keeps depth untouched where nothing is drawn
        }
        return o;
    }
    if (ogFx == 11) {
        // gpu sparks: palette by param.y (0 rainbow, 1 plasma, 2 electric), fade by age
        float age = clamp(ogParam.x + fract(t) / 15.0, 0.0, 1.0);
        int pal = int(ogParam.y * 15.0 + 0.5);
        vec3 c;
        if (pal == 0) {
            c = og_hsv2rgb(vec3(fract(ogChain * 8.0 + t * 0.05), 0.8, 1.0));
        } else if (pal == 1) {
            c = mix(vec3(0.4, 0.7, 1.0), vec3(1.0), og_hash(ogChain * 31.0));
        } else if (pal == 3) {
            c = mix(vec3(0.55, 0.25, 1.0), vec3(1.0, 0.9, 1.0), og_hash(ogChain * 17.0));
        } else if (pal == 4) {
            c = mix(vec3(1.0, 0.45, 0.1), vec3(1.0, 0.9, 0.4), og_hash(ogChain * 23.0));
        } else {
            c = mix(vec3(0.6, 0.8, 1.0), vec3(1.0), step(0.5, og_hash(floor(t * 2.0) + ogChain * 13.0)));
        }
        float flick = 0.7 + 0.3 * og_hash(floor(t * 2.0) + ogChain * 5.0);
        return vec4(c * 1.4 * flick, (1.0 - age) * (1.0 - age) * tex.a);
    }
    if (ogFx == 16) {
        // capsule impostor: rebuild the quad's axes from screen-space derivatives, ray-cast a glowing
        // capsule along the longer axis. Works wherever the model ends up (hand transforms included).
        vec3 dPx = dFdx(ogPosV);
        vec3 dPy = dFdy(ogPosV);
        vec2 dLx = dFdx(ogLocal);
        vec2 dLy = dFdy(ogLocal);
        float det = dLx.x * dLy.y - dLy.x * dLx.y;
        if (abs(det) < 1e-9) {
            return vec4(0.0);
        }
        vec3 A = (dPx * dLy.y - dPy * dLx.y) / det;   // dP / dlocal.x
        vec3 B = (-dPx * dLy.x + dPy * dLx.x) / det;  // dP / dlocal.y
        vec3 p0;
        vec3 axis;
        float w;
        if (dot(A, A) >= dot(B, B)) {
            p0 = ogPosV - ogLocal.x * A - (ogLocal.y - 0.5) * B;
            axis = A;
            w = length(B);
        } else {
            p0 = ogPosV - ogLocal.y * B - (ogLocal.x - 0.5) * A;
            axis = B;
            w = length(A);
        }
        vec3 rd = normalize(ogPosV);
        float d = og_ray_seg(rd, p0, p0 + axis);
        vec3 col = vec3(1.0, 0.6, 0.2);
        if (ogSubI == 1) {
            col = vec3(1.0, 0.5, 0.12);
        } else if (ogSubI == 2) {
            col = vec3(0.6, 0.3, 1.0);
        }
        float core = smoothstep(0.18 * w, 0.0, d);
        float halo = exp(-pow(d / (0.36 * w), 2.0));
        float hum = 0.85 + 0.15 * sin(t * 0.8);
        float facing = abs(dot(normalize(ogNrmV), rd));
        vec3 c = col * halo * 1.7 + vec3(1.0) * core;
        float a = clamp((core + halo * 0.9) * hum, 0.0, 1.0) * (0.35 + 0.65 * facing) * (1.0 - ogParam.y);
        if (a < 0.02) {
            return vec4(0.0);
        }
        return vec4(c, a);
    }
    if (ogFx == 17) {
        // chrono shell: big sphere, shaded from outside and inside; hex lattice + clock sweep
        vec3 rd = normalize(ogPosV);
        vec3 c = ogCenterV;
        float r = 0.3 + 3.2 * ogParam.x;
        float fade = ogParam.y;
        float b = dot(rd, c);
        float cc = dot(c, c);
        float det = b * b - cc + r * r;
        if (det < 0.0) {
            return vec4(0.0);
        }
        bool inside = cc < r * r;
        float th = inside ? b + sqrt(det) : b - sqrt(det);
        if (th < 0.05) {
            return vec4(0.0);
        }
        vec3 p = rd * th;
        vec3 nOut = (p - c) / r;
        vec3 n = inside ? -nOut : nOut;
        vec3 nw = transpose(mat3(ModelViewMat)) * nOut;
        vec2 uv = vec2(atan(nw.z, nw.x) * 2.2, asin(clamp(nw.y, -1.0, 1.0)) * 2.2) * 1.6;
        vec4 hx = og_hexcoords(uv);
        float line = smoothstep(0.07, 0.0, hx.y);
        float cell = og_hash(dot(hx.zw, vec2(12.9898, 78.233)));
        float pulse = 0.5 + 0.5 * sin(t * 0.3 + cell * 6.2831);
        float band = fract(atan(nw.z, nw.x) / 6.2831 - t * 0.012);
        float clock = smoothstep(0.05, 0.0, band);
        float fres = pow(1.0 - max(dot(n, -rd), 0.0), 2.0);
        vec3 refr = refract(rd, n, 0.85);
        vec3 dw = transpose(mat3(ModelViewMat)) * refr;
        vec3 star = og_portal(dw, t * 0.5, 0.0) * vec3(0.5, 0.9, 1.0) * 0.4;
        vec3 col = vec3(0.3, 0.85, 1.0) * (line * 1.4 + clock * 1.2 + pulse * 0.08) + star + fres * vec3(0.4, 0.8, 1.0) * 0.8;
        float a = inside
            ? clamp(line * 0.8 + clock * 0.5 + 0.06, 0.0, 0.7)
            : clamp(0.22 + line * 0.7 + clock * 0.5 + fres * 0.5, 0.0, 0.9);
        a *= (1.0 - fade);
        if (a < 0.03) {
            return vec4(0.0);
        }
        return vec4(col, a);
    }
    if (ogFx == 18) {
        // fireball: sphere with animated fire noise, dark smoky rim
        vec3 rd = normalize(ogPosV);
        vec3 c = ogCenterV;
        float r = 0.25 + 0.65 * ogParam.x;
        float b = dot(rd, c);
        float det = b * b - dot(c, c) + r * r;
        if (det < 0.0) {
            return vec4(0.0);
        }
        float th = b - sqrt(det);
        if (th < 0.05) {
            return vec4(0.0);
        }
        vec3 p = rd * th;
        vec3 n = (p - c) / r;
        vec3 nw = transpose(mat3(ModelViewMat)) * n;
        float f = sin(nw.x * 6.0 + t * 0.9) * sin(nw.y * 5.0 - t * 0.7);
        f += 0.5 * sin(nw.z * 9.0 + t * 1.3 + nw.x * 4.0);
        f += 0.6 * og_hash(floor(nw.x * 8.0) + floor(nw.y * 8.0) * 7.0 + floor(nw.z * 8.0) * 13.0 + floor(t * 1.5));
        f = clamp(f * 0.45 + 0.5, 0.0, 1.0);
        vec3 col = mix(vec3(0.9, 0.15, 0.02), vec3(1.0, 0.6, 0.1), smoothstep(0.2, 0.6, f));
        col = mix(col, vec3(1.0, 0.95, 0.7), smoothstep(0.7, 0.95, f));
        float fres = pow(1.0 - max(dot(n, -rd), 0.0), 2.0);
        col = mix(col, vec3(0.25, 0.08, 0.02), fres * 0.7);
        col += fres * vec3(1.0, 0.5, 0.1) * 0.3;
        return vec4(col * 1.3, (1.0 - ogParam.y) * tex.a);
    }
    if (ogFx == 19) {
        // gravity well: black sphere with violet horizon, lensed starfield halo around the silhouette
        vec3 rd = normalize(ogPosV);
        vec3 c = ogCenterV;
        float collapse = ogParam.y;
        float r = (0.15 + 0.5 * ogParam.x) * (1.0 - 0.9 * collapse);
        float b = dot(rd, c);
        float cc = dot(c, c);
        float det = b * b - cc + r * r;
        float dist = sqrt(max(cc - b * b, 0.0));
        if (det >= 0.0) {
            float th = b - sqrt(det);
            if (th < 0.05) {
                return vec4(0.0);
            }
            vec3 p = rd * th;
            vec3 n = (p - c) / r;
            float fres = pow(1.0 - max(dot(n, -rd), 0.0), 4.0);
            vec3 col = vec3(0.01, 0.0, 0.02) + fres * vec3(0.7, 0.35, 1.0) * (1.5 + 3.0 * collapse);
            return vec4(col, 1.0);
        }
        float halo = 2.2 * r;
        if (dist > halo || b < 0.05) {
            return vec4(0.0);
        }
        vec3 closest = rd * b;
        vec3 toC = normalize(c - closest);
        vec3 bent = normalize(rd + toC * (r / max(dist, 1e-3)) * 0.8);
        vec3 dw = transpose(mat3(ModelViewMat)) * bent;
        vec3 star = og_portal(dw, t, 0.0) * 2.2;
        float ring = smoothstep(halo, r, dist);
        float a = ring * ring * 0.9 * (1.0 - collapse * 0.3);
        vec3 col = star * (0.6 + 0.4 * ring) + vec3(0.5, 0.25, 0.9) * ring * ring * 0.5;
        if (a < 0.03) {
            return vec4(0.0);
        }
        return vec4(col, a);
    }
    if (ogFx == 15) {
        // tesla sphere: ray-cast like the nova orb; electric cyan starfield, jumping crackle
        // flecks, flickering rim; param.y = zap surge (bigger + whiter for a few ticks)
        vec3 rd = normalize(ogPosV);
        vec3 c = ogCenterV;
        float surge = ogParam.y;
        float r = 0.2 * (1.0 + 0.3 * surge) + 0.012 * sin(t * 0.6);
        float b = dot(rd, c);
        float det = b * b - dot(c, c) + r * r;
        if (det < 0.0) {
            return vec4(0.0);
        }
        float th = b - sqrt(det);
        if (th < 0.05) {
            return vec4(0.0);
        }
        vec3 p = rd * th;
        vec3 n = (p - c) / r;
        vec3 refr = refract(rd, n, 0.74);
        vec3 dw = transpose(mat3(ModelViewMat)) * refr;
        vec3 col = og_portal(dw, t * 1.7, 0.0) * vec3(0.55, 1.0, 1.25);
        float seed = floor(t * 2.5);
        float fleck = step(0.965, og_hash(seed * 3.1 + floor(dot(n, vec3(3.0, 5.0, 7.0)) * 9.0) * 0.37));
        col += fleck * vec3(0.8, 0.95, 1.0) * 1.5;
        float flick = 0.75 + 0.25 * og_hash(seed + 0.5);
        float fres = pow(1.0 - max(dot(n, -rd), 0.0), 2.5);
        col += fres * vec3(0.45, 0.85, 1.0) * 1.4 * flick;
        col += vec3(0.05, 0.12, 0.2) * flick;
        col = mix(col, vec3(1.0), surge * 0.45);
        float a = (0.9 + 0.1 * fres) * (1.0 - ogParam.x);
        return vec4(col, a);
    }
    if (ogFx == 14) {
        // nova sphere: ray-cast a sphere of radius (charge) around the billboard centre;
        // surface = refracted parallax starfield + fresnel rim in the charge colour
        vec3 rd = normalize(ogPosV);
        vec3 c = ogCenterV;
        float r = (0.16 + 0.34 * ogParam.x) * (1.0 - 0.85 * ogParam.y);
        float b = dot(rd, c);
        float det = b * b - dot(c, c) + r * r;
        if (det < 0.0) {
            return vec4(0.0);
        }
        float th = b - sqrt(det);
        if (th < 0.05) {
            return vec4(0.0);
        }
        vec3 p = rd * th;
        vec3 n = (p - c) / r;
        vec3 refr = refract(rd, n, 0.74);
        vec3 dw = transpose(mat3(ModelViewMat)) * refr;
        vec3 col = og_portal(dw, t, ogParam.x);
        float fres = pow(1.0 - max(dot(n, -rd), 0.0), 3.0);
        vec3 rimCol = mix(vec3(0.3, 0.6, 1.0), vec3(1.0, 0.92, 0.7), ogParam.x);
        col += fres * rimCol * 1.3;
        col += (0.15 + 0.25 * ogParam.x) * rimCol * (0.6 + 0.4 * sin(t * 0.5));
        float a = (0.9 + 0.1 * fres) * (1.0 - ogParam.y);
        return vec4(col, a);
    }
    if (ogFx == 12) {
        // blade swing ghost: hue-shifted translucent copy, fades with param.x, hue offset param.y
        float h = fract(og_hue(tex.rgb) + t * 0.03 + ogParam.y * 0.3);
        vec3 c = og_hsv2rgb(vec3(h, 0.55, 1.0));
        float a = tex.a * 0.55 * (1.0 - ogParam.x);
        if (a < 0.02) {
            return vec4(0.0);
        }
        return vec4(c * 1.1, a);
    }
    return tex;
}

// holo edge (FX 13): chromatic split (neighbour samples passed in from main), scanlines, rare flicker
vec4 og_holo(vec4 tex, float rr, float bb) {
    float t = GameTime * 24000.0;
    if (ogGui == 1) {
        return tex;
    }
    vec3 c = vec3(rr, tex.g, bb);
    float scan = 0.88 + 0.12 * sin(gl_FragCoord.y * 1.7 + t * 1.5);
    float flick = 1.0 - 0.25 * step(0.985, og_hash(floor(t * 1.5)));
    return vec4(c * 1.12 * scan * flick, tex.a);
}
// ---- end OrangeGames FX decl ----

uniform sampler2D Sampler0;

in float sphericalVertexDistance;
in float cylindricalVertexDistance;
in vec4 vertexColor;
in vec2 texCoord0;
in vec2 texCoord1;

out vec4 fragColor;

void main() {

    // ---- OrangeGames FX ----
    if (ogFx != 0) {
        vec4 ogTex = texture(Sampler0, texCoord0);
        vec4 ogC;
        if (ogFx == 13) {
            vec2 ogPx = 1.0 / vec2(textureSize(Sampler0, 0));
            float ogOff = 0.6 + 0.6 * sin(GameTime * 24000.0 * 0.7);
            ogC = og_holo(ogTex,
                          texture(Sampler0, texCoord0 + vec2(ogPx.x * ogOff, 0.0)).r,
                          texture(Sampler0, texCoord0 - vec2(ogPx.x * ogOff, 0.0)).b);
        } else {
            ogC = og_fx(ogTex);
        }
        if (ogC.a <= 0.0) {
            discard;
        }
        ogC *= ColorModulator;

        fragColor = apply_fog(ogC, sphericalVertexDistance, cylindricalVertexDistance, FogEnvironmentalStart, FogEnvironmentalEnd, FogRenderDistanceStart, FogRenderDistanceEnd, FogColor);
        return;
    }
    // ---- end OrangeGames FX ----
    vec4 color = texture(Sampler0, texCoord0) * vertexColor * ColorModulator;
    if (color.a < 0.1) {
        discard;
    }
    fragColor = apply_fog(color, sphericalVertexDistance, cylindricalVertexDistance, FogEnvironmentalStart, FogEnvironmentalEnd, FogRenderDistanceStart, FogRenderDistanceEnd, FogColor);
}
